---
title: "Proposals"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Menno
darm-permeability
2 groepen, ~40 samples, focus op 1 gen (receptor), 103 DEGs gevonden

### Jack
MS (in muis en mens)
superserie, 3 subseries, 63 samples (8(2)/10(2)/45(4))
Eerst focus op 1 serie

### Rick
Wheat, *Grain Protein Content* genes
Eigen referentie (454), RNA-seq middels Illumina
7 samples (1 verwijderd), 3WT, 4MT

### Bas
Tijdseries, 3 tijdstippen
36-samples, Drosophila melanogaster

### Nathan
Cocaine in muizen
12-samples, tijdseries (3 tijdstippen, tot 14-dagen)

### Nils
ApoE; vetstofwisseling. HF-dieet en effect op Alzheimer, afhankelijk van variant ApoE
52 samples (muizen), 4 groepen, Weighted gene co-expression network analysis

### Aleksandra
Alzheimer, muizen (zie Kylie)
8 groepen, 3 reps. Leeftijd en type
-> goede visualisatie in artikel

### Marjan
9 (muis) samples, aging
Leeftijdscategorieen (3, 24, 29 maand oud)
DeXseq R-pakket
Re-do

### Marcel
Longziekte (Idiopathic Pumonary Fibrosis), littekenweefsel
3 groepen (Control(8)/IPFnormal(10)/IPFscarred(8))
Re-do

### Willemijn
aT-catenine (eiwitten voor orgaan structuur/ functie) in relatie tot autisme
6 samples (3WT/3KO), muis
edgeR
Re-do

### Olle
Huntington, invloed heeft op skeletspieren
80 samples (4WT(2 spiergroepen, behandeld/nietbehandeld), 4R6/2(2 spiergroepen, behandeld/nietbehandeld)), muis

### Kylie
Alzheimer (zie Aleksandra) 
WGCENA

### Wouter
Crohn
3 sample-groepen (Control + 2 genotype groepen)

### Hylke
Ruwe-data processing
Muis, 2 leeftijden, 19 samples
Eigen idee, vergelijking tussen hersen gebieden i.p.v. leeftijden

### Maarten
Leukemie in de muis
12 samples, 4 groepen
Re-do (verschil WT/KO) + uitbreiding

### Rinze-Pieter
Arabidopsis
24 samples, 4 groepen, elk in twee categorien (wel/geen stress)
Re-do

### Ilse
Zeekomkommer in verschillende zout-concentraties
60 samples, 3 groepen (control, lage & hoge zout-concentraties)
per groep 9 onderzocht (v/d 20)

### Niels
Embryonale hematopoietische stamcellen
4 groepen, 319 samples (min. 49/groep)

### Jouke
Epigenetics (verzwakte DNA-replicatie)
Rondwormen, 2 groepen, 3 replicaten

### Max
Effect Traditionele Chinese Medicatie op kanker
27 samples, tijdseries (control, 2x behandeld (hoeveelheid), medicatie-control)
MCF-7 cellijn
Pathway analysis
Re-do

### Wendy
Asthma inductie in muizen, zorgt voor autisme bij offspring
Superseries (RNA-Seq + DNA-methylatie). 2 groepen (asthma offspring/control), 8 samples per subseries
Re-do + mogelijk methylatie data analyse

## Notes

* Z-score berekening
* Annotatie
* Samenwerking tussen groepen uitzoeken