<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title> Discovering Differentialy Expressed Genes (DEGs) | Transcriptomics Project - Gene Expression Analysis</title>
<meta name="author" content="Marcel Kempenaar">
<meta name="description" content="The first and most important ‘real’ analysis step we will do is finding genes that show a difference in expression between sample groups; the differentially expressed genes (DEGs). The concept...">
<meta name="generator" content="bookdown 0.46 with bs4_book()">
<meta property="og:title" content=" Discovering Differentialy Expressed Genes (DEGs) | Transcriptomics Project - Gene Expression Analysis">
<meta property="og:type" content="book">
<meta property="og:description" content="The first and most important ‘real’ analysis step we will do is finding genes that show a difference in expression between sample groups; the differentially expressed genes (DEGs). The concept...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content=" Discovering Differentialy Expressed Genes (DEGs) | Transcriptomics Project - Gene Expression Analysis">
<meta name="twitter:description" content="The first and most important ‘real’ analysis step we will do is finding genes that show a difference in expression between sample groups; the differentially expressed genes (DEGs). The concept...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.10.0/transition.js"></script><script src="libs/bs3compat-0.10.0/tabs.js"></script><script src="libs/bs3compat-0.10.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Transcriptomics Project - Gene Expression Analysis</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="" href="chapter-1.html"><span class="header-section-number">1</span> Introduction</a></li>
<li><a class="" href="chapter-2.html"><span class="header-section-number">2</span> Discovering Data Sets</a></li>
<li><a class="" href="chapter-3.html"><span class="header-section-number">3</span> Exploratory Data Analysis</a></li>
<li><a class="active" href="chapter-4.html"><span class="header-section-number">4</span> Discovering Differentialy Expressed Genes (DEGs)</a></li>
<li><a class="" href="chapter-5.html"><span class="header-section-number">5</span> Data Analysis and Visualization</a></li>
<li class="book-part">Appendix</li>
<li><a class="" href="a1-batch_data_loading.html"><span class="header-section-number">A</span> Appendix A: Batch Loading Expression Data in R</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="chapter-4" class="section level1" number="4">
<h1>
<span class="header-section-number"></span> Discovering Differentialy Expressed Genes (DEGs)<a class="anchor" aria-label="anchor" href="#chapter-4"><i class="fas fa-link"></i></a>
</h1>
<p>The first and most important ‘real’ analysis step we will do is finding genes that show a difference in expression between sample groups; the <em>differentially expressed genes</em> (DEGs). The concept might sound rather simple; calculate the ratios for all genes between samples to determine the <strong>fold-change</strong> (FC) denoting the factor of change in expression between groups. Then, filter out only those genes that actually show a difference. While this does give a list of genes showing different behaviour across samples, we need to focus on genes that do not only show a difference, but are also <em>statistically significant</em>!</p>
<p>To determine whether or not a gene can be classified as a significant DEG we are going to use - at least - two techniques:</p>
<ul>
<li>We will start with manually performing statistical test(s)</li>
<li>and compare these results from those given by using one or more R (Bioconductor) libraries (mostly <code>edgeR</code> and <code>DESeq2</code>)</li>
</ul>
<div id="deg-preprocessing" class="section level2" number="4.1">
<h2>
<span class="header-section-number">4.1</span> Pre-processing<a class="anchor" aria-label="anchor" href="#deg-preprocessing"><i class="fas fa-link"></i></a>
</h2>
<p>Given the results of the exploratory data analysis performed in <a href="chapter-3.html#chapter-3">chapter 3</a>, you might have concluded that there are one or more samples that show (very) deviating expression patterns compared to samples from the same group. As mentioned before, <em>if</em> you have more then enough (&gt; 3) samples in a group, you might opt to remove a sample to reduce the noise as the statistical tests are very sensitive to this. Since we are performing all analysis steps programatically it is also very easy to test for DEGs with and without the sample(s) in question and see if the removal results in lower p-values (= higher significance). If this is the case you can continue on without those sample(s). As always, be sure to properly document this, including the reason why you chose to remove them.</p>
<p>Another step we need to take - and this might be guided by your article - is to filter out (partially) inactive genes. Most datasets available contains a lot of 0-measurements, transcripts where no reads have mapped. In the R-studio <em>Environment</em> tab, click on your dataset (or perform the <code>View(data)</code> command and click on one of the sample columns to order the data ascending. You will now most likely (unless you have bacterial data for instance) see a lot of zero values in all columns. In an experiment with two groups, three replicates each, if three out of those six samples have 0-reads mapped, it is often adviced to remove the gene completely. But this can be very subjective to the experiment, it might be expected (thus important) when comparing different tissues or knockout experiments. Also, genes with a (very) low read count (&lt; 5) can give a very high (artificial) FC value (see the lefthand side of an MA-plot). Comparing two samples where one has a value of 2 and the other 11, this reads as an up-regulated gene by a factor of <em>5.5</em> while it might actually just be <em>noise</em>!</p>
<ul>
<li>
<strong>Assignment</strong>: Search through your article for any advice on how to filter out zero values or low count genes. If there is nothing stated on this subject, think of your own tactic (or search the literature/ online!). It is perfectly fine to discuss with your peers.
<ul>
<li>
<strong>describe</strong> what you will be doing for this aspect; if you do <em>not</em> filter your data, clearly explain why not (most likely because the article stated a proper reason)</li>
<li>Perform the filtering on your dataset. For this you will most likely need to use one of the <code>apply</code>, <code>rowSums</code>, <code>rowMeans</code> functions, combined with maybe the <code>which</code>, <code>all</code> and <code>any</code> functions. Data transformations/ normalizations are often available from functions too, such as the <code>cpm</code> function from the <code>edgeR</code> library.</li>
<li>Manually verify that the rows removed were correctly filtered.</li>
<li>Properly document how many genes have been filtered out!</li>
</ul>
</li>
</ul>
</div>
<div id="deg-fc" class="section level2" number="4.2">
<h2>
<span class="header-section-number">4.2</span> The <em>Fold Change</em> Value<a class="anchor" aria-label="anchor" href="#deg-fc"><i class="fas fa-link"></i></a>
</h2>
<p>The FC is usually given as the calculated <code>log2</code> of the <em>case/control</em> ratio. For example, gene A has an average expression of 30 mapped reads in the control group and 88 reads in the experiment group, the <strong>ratio</strong> <em>case/control</em> is <code>2.93</code>. Ratio values &gt; 1 indicate increased expression in the experiment in relation to the control and values between 0 and 1 indicate lower expression. The log2 transformed value of the ratio is calculated with <code>log2(2.93)</code> and results in <code>1.55</code>. If the counts were reversed, the ratio would have been <code>30/88</code>, which is <code>0.34</code>. The previously calculated value of <code>2.93</code> means a 3-fold up regulation while the <code>0.34</code> value means 3-fold down regulation but you can see the range of numbers is very different. Comparing log2 values this would be <code>1.55</code> and <code>-1.55</code> which compares much better.</p>
<p>While it is very easy to calculate the FC for all genes at once, a simple FC value doesn’t mean much, yet! We still need to use the power that lie within the replicates we have for each sample group. Using these replicates, we want to determine if the observed FC is not just biological noise or a sequencing error.</p>
<ul>
<li>
<strong>Assignment</strong>: Create a <code>histogram</code> of your log2-FC values for <em>all</em> genes. Apply the following steps on your <em>normalized data</em> to do this for at least one comparison (no need to do it for all possible combinations):
<ul>
<li>average the replicates for each group and add this as a new column to your data set,</li>
<li>calculate the ratios; simply divide one group (averaged-column) by another, usually <code>experiment</code>/<code>control</code>,</li>
<li>perform a log2-transformation (now you have the <code>log2-FC</code> values),</li>
<li>plot the data using the <code>hist(logFC_column, breaks=60)</code> function (change the <code>breaks</code> argument if needed),</li>
<li>Add two vertical lines at <code>-1</code> and <code>1</code> (using <code>abline(v=...)</code>) to indicate some significance (2-fold change).</li>
</ul>
</li>
</ul>
<p>If a calculated FC shows a large change in expression between groups this means nothing if the variation <em>within</em> a group is very high. For this reason we use some form of statistical test that checks both the variation in each group <em>and</em> the difference between groups of samples. In the simplest form this usually comes down to using a <a href="https://en.wikipedia.org/wiki/Student%27s_t-test"><em>t</em>-test</a>:</p>
<blockquote>
<p>“It can be used to determine if two sets of data are significantly different from each other”</p>
</blockquote>
<p>It does however depend on your experimental setup when it comes down to deciding the proper statistical test to perform and for that it is best to look at your experiment article to see what the authors used for method. Most often though, the article only mentions the use of one or more R libraries of other software packages for finding DEGs. In this case you can find the appropriate method by determining the possible combinations to test.</p>
<p>The output of finding DEG’s always includes - but is not limited to - a list of <em>p-values</em>; usually one p-value per gene. This value indicates whether that gene is a <em>statistically-significant differentially expressed gene</em> (SDEG) and to find these genes of interest all we need to do is get all genes with a p-value below our threshold (i.e. <code>0.05</code>). Because we will get at least two p-values per gene (one found using manually statistical testing and one through the use of a library) we can make multiple selections, i.e. compare methods, find genes that have a low p-value in both methods and visualize these results in a <em>venn-diagram</em> (see section <a href="#deg-visualization">visualization</a>).</p>
</div>
<div id="deg-manual" class="section level2" number="4.3">
<h2>
<span class="header-section-number">4.3</span> Using Manual Methods (<code>t-test</code> &amp; <code>ANOVA</code>)<a class="anchor" aria-label="anchor" href="#deg-manual"><i class="fas fa-link"></i></a>
</h2>
<p>Performing the statistical tests yourself consists of performing either a t-test or an ANOVA based analysis. Both of these methods have multiple forms and the one to choose fully depends on what question you’d like to ask. Again, refer to your experimental setup and any hints found in the article <em>or</em> formulate your own question and base the decision on that.</p>
<p>Manually performing a t-test or ANOVA on gene expression opposed to using one of the specialized libraries can have advantages since every gene is processed individually, while <code>edgeR</code> and <code>DESeq2</code> look at <em>all</em> genes and this might ‘smooth’ the results which is not always wanted. We will find out later if and how this affects your data set.</p>
<p>If your data <strong>only</strong> consists of the read counts there is an extra normalisation step to perform (only for the manual methods explained in this section, keep the count data stored as well!). One generally accepted method of normalizing count data is to calculate the <em>fragments per million mapped fragments</em> (FPM) value and then transform this with log2. Opposed to FPKM and RPKM this does not include the gene-length in its calculation (which you most likely don’t have) but as said before we apply the test per gene and do not need to compare multiple genes. If your dataset also includes FPKM or RPKM (pre-normalized), you are allowed to use this data too. Always clearly document if you did so! Once you performed a manual statistical test, be sure to read the section on <a href="chapter-4.html#deg-mtc">Multiple Testing Correction</a> further on in this chapter.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Perform FPM normalization using DESeq2 'fpm' and perform log2 transformation</span></span>
<span><span class="co"># The 'ddsMat' object is the 'DESeqDataSet' created in chapter 3; EDA.</span></span>
<span><span class="co"># NOTE: only for count data and observe the pseudocount of 1 (remove if data does not contain 0-values)</span></span>
<span><span class="va">counts.fpm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log2</a></span><span class="op">(</span> <span class="fu"><a href="https://rdrr.io/pkg/DESeq2/man/fpm.html">fpm</a></span><span class="op">(</span><span class="va">ddsMat</span>, robust <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span> <span class="fl">1</span> <span class="op">)</span></span></code></pre></div>
<p>Next is selecting the test to perform, the following links show diagrams that can be used once the experimental design is known:</p>
<p><em>What test to use</em> links:</p>
<ul>
<li><a href="https://stats.idre.ucla.edu/other/mult-pkg/whatstat/choosestat-html/">Institute for Digital Research and Education</a></li>
<li><a href="http://www.biochemia-medica.com/content/comparing-groups-statistical-differences-how-choose-right-statistical-test">Biochemia - image at the bottom of the article</a></li>
<li><a href="http://www.practicallyscience.com/wp-content/uploads/2015/07/significance-tests-v4-op2.jpg">PracticallyScience</a></li>
</ul>
<p>These examples may include terms that are unclear. If so, please ask or perform a standard internet search as these terms are explained in multiple tutorials about performing these widely used statistical tests.</p>
<ul>
<li>
<strong>Assignment</strong>: Think of a question (i.e. a comparison between two or more sample groups) to ask the data and perform a statistical test to find the relevant genes for this question. Briefly explain this comparison (maybe it was the one resulting in the most interesting results listed in the article) and introduce the test that you are going to perform.
<ul>
<li>Report on the number of significant genes before <em>and</em> after <a href="chapter-4.html#deg-mtc">Multiple Testing Correction</a> for each comparison that has been done.</li>
</ul>
</li>
</ul>
<div id="deg-ttest" class="section level3" number="4.3.1">
<h3>
<span class="header-section-number">4.3.1</span> Students T-test<a class="anchor" aria-label="anchor" href="#deg-ttest"><i class="fas fa-link"></i></a>
</h3>
<p>In order to test if one or more genes are significantly differentially expressed between a maximum of two conditions one can perform a t-test. The t-test will test the <em>null hypothesis</em> that there is no difference between the mean of the two populations. Usually, if the p-value is below the significance threshold chosen (also called alpha-value, usually set at <span class="math inline">\(\alpha\)</span> <code>0.05</code>) you reject the null hypothesis and conclude that there is a significant difference between the means.</p>
<div class="rmdtip">
<p>
Note that it is necessary to perform a single t-test for
<em>every</em> gene (row) of your data set, including all replicates for
the involved group. This means that you need to either use one of the
<code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> set of functions or find a different method (there
is one specifically for this problem) to make sure that you test each
gene separately. From the output of the t-test you only need to keep the
calculated <em>p-value</em>; one value per gene (row) in your data set.
In R, you can append this as a column to your dataframe/ matrix
containing the normalized count values.
</p>
</div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Note: Single-gene only example</span></span>
<span><span class="co">## Convert to simple numeric vectors, used for the variance test</span></span>
<span><span class="va">ipsc.exp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">counts.fpm</span><span class="op">[</span><span class="st">"KCTD14"</span>, <span class="va">di_IPSC</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">neur.exp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">counts.fpm</span><span class="op">[</span><span class="st">"KCTD14"</span>, <span class="va">di_NEUR</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="width:100%;" class="table table-sm">
<caption>Data for t-test, di_IPSC (case, 3 samples) vs di_NEUR (control, 3 samples), “KCTD14” gene</caption>
<colgroup>
<col width="16%">
<col width="16%">
<col width="16%">
<col width="16%">
<col width="16%">
<col width="16%">
</colgroup>
<thead><tr class="header">
<th align="center">di_IPSC_r1</th>
<th align="center">di_IPSC_r2</th>
<th align="center">di_IPSC_r3</th>
<th align="center">di_NEUR_r1</th>
<th align="center">di_NEUR_r2</th>
<th align="center">di_NEUR_r3</th>
</tr></thead>
<tbody><tr class="odd">
<td align="center">4.39</td>
<td align="center">4.36</td>
<td align="center">4.456</td>
<td align="center">1.102</td>
<td align="center">1.083</td>
<td align="center">1.058</td>
</tr></tbody>
</table></div>
<p>First, we test (F-test) if the variance (the average of the squared differences from the mean) in the two sample groups is equal as we need to supply the t-test with this information (by default, it assumes different variance). Note that before performing an F-test, it should first be validated that the data is normally distributed, i.e. using a Shapiro-Wilk test (you are <strong>not</strong> expected to do this test too, as a dataset with a three-replicate setup does not provide enough information for this test).</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Test for equal variance (H0 = 'equal variance')</span></span>
<span><span class="va">variance</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/var.test.html">var.test</a></span><span class="op">(</span><span class="va">ipsc.exp</span>, <span class="va">neur.exp</span>, alternative <span class="op">=</span> <span class="st">'two.sided'</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>F test to compare two variances: <code>ipsc.exp</code> and <code>neur.exp</code>
</caption>
<colgroup>
<col width="18%">
<col width="9%">
<col width="11%">
<col width="10%">
<col width="26%">
<col width="22%">
</colgroup>
<thead><tr class="header">
<th align="center">Test statistic</th>
<th align="center">num df</th>
<th align="center">denom df</th>
<th align="center">P value</th>
<th align="center">Alternative hypothesis</th>
<th align="center">ratio of variances</th>
</tr></thead>
<tbody><tr class="odd">
<td align="center">5.03</td>
<td align="center">2</td>
<td align="center">2</td>
<td align="center">0.3317</td>
<td align="center">two.sided</td>
<td align="center">5.03</td>
</tr></tbody>
</table></div>
<p>In this case, it seems that the variance does <strong>not</strong> differ significantly (P-value of <code>0.3317</code> &gt; <code>0.05</code>) between the two sample groups, therefore set the <code>var.equal</code> argument in the <code>t.test</code> function to <code>TRUE</code>. Most experiments are unpaired; meaning that the expression for a replicate in group A is from a different subject/ person then the expression for a replicate in group B. If however you have time-series data where the same subjects/ persons are used in multiple sample groups, you should set the <code>paired</code> option in the <code>t.test</code> function to <code>TRUE</code>. In most other situations, keep this setting to its default; <code>FALSE</code>.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">ipsc.exp</span>, <span class="va">neur.exp</span>, alternative <span class="op">=</span> <span class="st">'two.sided'</span>, var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<p>The following table shows the numeric values from performing a t-test. Here we see that this gene is identified as a DEG because its <span class="math inline">\(\alpha\)</span> &lt; <code>0.05</code>. Since the t-test compares the mean of two groups, the difference between these two values (4.4 for the ‘IPSC’ group and 1.08 for the ‘NEURON’ group) are deemed significant. Do note that ‘noise’ (often a large variance within a group of replicates) has a lot of effect on the p-value.</p>
<div class="inline-table"><table class="table table-sm">
<caption>Two Sample t-test: <code>ipsc.exp</code> and <code>neur.exp</code>
</caption>
<colgroup>
<col width="19%">
<col width="5%">
<col width="20%">
<col width="28%">
<col width="13%">
<col width="13%">
</colgroup>
<thead><tr class="header">
<th align="center">Test statistic</th>
<th align="center">df</th>
<th align="center">P value</th>
<th align="center">Alternative hypothesis</th>
<th align="center">mean of x</th>
<th align="center">mean of y</th>
</tr></thead>
<tbody><tr class="odd">
<td align="center">106.5</td>
<td align="center">4</td>
<td align="center">4.665e-08 * * *</td>
<td align="center">two.sided</td>
<td align="center">4.402</td>
<td align="center">1.081</td>
</tr></tbody>
</table></div>
<p>Again, we are only interested in the p-value for each gene, store this in either the original data frame or a new one where it is coupled to the gene identifier (name, symbol, etc.).</p>
<p><em>t.test</em> tutorials:</p>
<ul>
<li><a href="https://bioinf.nl/~michiel/courses/R_minor/ttest.html#the-t-test">M. A. Noback, DAVuR Course Syllabus</a></li>
<li><a href="http://www.statmethods.net/stats/ttest.html">Quick-R @ statmethods</a></li>
<li>
<a href="http://jura.wi.mit.edu/bio/education/bioinfo2007/arrays/array_exercises_2R.html">Whitehead Institute</a>: based on microarray analysis, but it’s still expression data and the basics are the same.</li>
</ul>
</div>
<div id="deg-anova" class="section level3" number="4.3.2">
<h3>
<span class="header-section-number">4.3.2</span> Analysis of Variance (<code>ANOVA</code>)<a class="anchor" aria-label="anchor" href="#deg-anova"><i class="fas fa-link"></i></a>
</h3>
<p>If you have decided that you need to perform ANOVA analysis, the experimental design as well as the question to ask become much more important. Usually it is required to perform ANOVA instead of a t-test when there are multiple (&gt; 2) conditions involved or it is a time series experiment. It is impossible to compare more than two conditions using a t-test unless using a <em>divide-and-conquer</em> approach (comparing all conditions against each other) but this is advised against since it will introduce Type I errors (false-positives). Experiments where conditions are combined (i.e. age + multiple drugs) can also be analysed using ANOVA where the question can either be the overall effect of a drug or the influence of age on the effect of a drug. The method of specifying these questions uses the same formula notation as for example the linear model (<code>lm</code>) function, i.e. <code>~ group + treatment + group:treatment</code> where group could be an <em>age</em> group and treatment a different <em>drug</em>. The most simple form of this formula is <code>~ condition</code>. Note that in this case condition is most likely an R <code>factor</code> dividing the samples in <em>case</em>/ <em>control</em> groups.</p>

<div class="rmdtip">
<p>Let us first consider a theoretical example and work towards a practical example in R. Given an experiment with <span class="math inline">\(k\)</span> conditions as shown in the table below where each gene <span class="math inline">\(i\)</span> is measured <span class="math inline">\(n_i\)</span> times.</p>
<div class="inline-table"><table class="table table-sm">
<caption><span class="math inline">\(Condition\)</span></caption>
<thead><tr class="header">
<th align="left">1</th>
<th align="left">2</th>
<th align="left">…</th>
<th align="left">i</th>
<th align="left">…</th>
<th align="left"><span class="math inline">\(k\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(X_{11}\)</span></td>
<td align="left"><span class="math inline">\(X_{21}\)</span></td>
<td align="left">…</td>
<td align="left"><span class="math inline">\(X_{i1}\)</span></td>
<td align="left">…</td>
<td align="left"><span class="math inline">\(X_{k1}\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(X_{12}\)</span></td>
<td align="left"><span class="math inline">\(X_{22}\)</span></td>
<td align="left">…</td>
<td align="left"><span class="math inline">\(X_{i2}\)</span></td>
<td align="left">…</td>
<td align="left"><span class="math inline">\(X_{k2}\)</span></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left">…</td>
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left">…</td>
<td align="left"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(X_{1n_{1}}\)</span></td>
<td align="left"><span class="math inline">\(X_{2n_{2}}\)</span></td>
<td align="left">…</td>
<td align="left"><span class="math inline">\(X_{in_{i}}\)</span></td>
<td align="left">…</td>
<td align="left"><span class="math inline">\(X_{kn_{k}}\)</span></td>
</tr>
</tbody>
</table></div>
<p>A typical question to ask is whether there are any differences between the expression level <span class="math inline">\(X\)</span> of the given gene between these conditions. However we need to carefully formulate the null and research hypotheses. The null hypothesis is pretty easy; <em>the different conditions are not really different and, therefore, all measurements actually come from a single distribution.</em> The effect is that all means would be the same, for all conditions: <span class="math inline">\(H_0 : \mu_{1} = \mu_{2} = \cdots = \mu_{k}\)</span>. It is not clear however whether the alternate or research hypothesis requires all <span class="math inline">\(k\)</span> conditions or a subset of these conditions to be different from each other. This results in the following three possible hypotheses for <span class="math inline">\(H_a\)</span>:</p>
<ol style="list-style-type: decimal">
<li>
<span class="math inline">\(H_a\)</span> : All means are different for each other.</li>
<li>
<span class="math inline">\(H_a\)</span> : Several but not all means are different from each other.</li>
<li>
<span class="math inline">\(H_a\)</span> : There is at least one pair of means that are different from each other.</li>
</ol>
<p>The first two hyptheses are not suitable for the question asked thus the following set of hypotheses remain:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{1} = \mu_{2} = \cdots = \mu_{k}\)</span></p>
<p><span class="math inline">\(H_a\)</span>: There is at least one pair of means that are different from each other.</p>
This set of hypotheses is called a <strong>Model I</strong> or <strong>fixed effects</strong>, <strong>ANOVA</strong>. The general idea behind this form of ANOVA is very simple. The measurements of each condition vary around the condition-mean (<em>within-group</em> variance). At the same time, the means of each condition will vary around an overall mean (<em>inter-group</em> variance). The idea behind ANOVA is to study the relationship between the inter-group and the within-group variances.
</div>
<p>The following practical example uses the <code>airway</code> experiment data package in R which contains RNA-Seq read count data for 8 samples. From the abstract, a brief description of the RNA-Seq experiment on airway smooth muscle (ASM) cell lines<span class="citation">(<a href="a1-batch_data_loading.html#ref-jiang14">Himes BE 2014</a>)</span>:</p>
<blockquote>
<p>Using RNA-Seq, a high-throughput sequencing method, we characterized transcriptomic changes in four primary human ASM cell lines that were treated with dexamethasone - a potent synthetic glucocorticoid (1 micromolar for 18 hours).</p>
</blockquote>
<p>The data available in the experiment package is of a certain <em>class</em> (Large <code>RangedSummarizedExperiment</code>) and contains both the count data as well as some metadata describing the experiment. Looking at the sample description table below, we can see a few columns describing variables that are used to define the experiment. In this case these are the <strong>cell</strong> (an identifier for a certain cell where each cell originates from the same subject) and <strong>dex</strong> (<code>trt</code> indicates treatment of each cell with 1 <span class="math inline">\(\mu M\)</span> <em>dexamethasone</em>, <code>untrt</code> indicates control) columns.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">airway</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">airway</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Sample description</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">colData</a></span><span class="op">(</span><span class="va">airway</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>Sample metadata for the airway experiment</caption>
<colgroup>
<col width="14%">
<col width="10%">
<col width="8%">
<col width="6%">
<col width="6%">
<col width="10%">
<col width="9%">
<col width="10%">
<col width="9%">
<col width="12%">
</colgroup>
<thead><tr class="header">
<th align="center"> </th>
<th align="center">SampleName</th>
<th align="center">cell</th>
<th align="center">dex</th>
<th align="center">albut</th>
<th align="center">Run</th>
<th align="center">avgLength</th>
<th align="center">Experiment</th>
<th align="center">Sample</th>
<th align="center">BioSample</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center"><strong>SRR1039508</strong></td>
<td align="center">GSM1275862</td>
<td align="center">N61311</td>
<td align="center">untrt</td>
<td align="center">untrt</td>
<td align="center">SRR1039508</td>
<td align="center">126</td>
<td align="center">SRX384345</td>
<td align="center">SRS508568</td>
<td align="center">SAMN02422669</td>
</tr>
<tr class="even">
<td align="center"><strong>SRR1039509</strong></td>
<td align="center">GSM1275863</td>
<td align="center">N61311</td>
<td align="center">trt</td>
<td align="center">untrt</td>
<td align="center">SRR1039509</td>
<td align="center">126</td>
<td align="center">SRX384346</td>
<td align="center">SRS508567</td>
<td align="center">SAMN02422675</td>
</tr>
<tr class="odd">
<td align="center"><strong>SRR1039512</strong></td>
<td align="center">GSM1275866</td>
<td align="center">N052611</td>
<td align="center">untrt</td>
<td align="center">untrt</td>
<td align="center">SRR1039512</td>
<td align="center">126</td>
<td align="center">SRX384349</td>
<td align="center">SRS508571</td>
<td align="center">SAMN02422678</td>
</tr>
<tr class="even">
<td align="center"><strong>SRR1039513</strong></td>
<td align="center">GSM1275867</td>
<td align="center">N052611</td>
<td align="center">trt</td>
<td align="center">untrt</td>
<td align="center">SRR1039513</td>
<td align="center">87</td>
<td align="center">SRX384350</td>
<td align="center">SRS508572</td>
<td align="center">SAMN02422670</td>
</tr>
<tr class="odd">
<td align="center"><strong>SRR1039516</strong></td>
<td align="center">GSM1275870</td>
<td align="center">N080611</td>
<td align="center">untrt</td>
<td align="center">untrt</td>
<td align="center">SRR1039516</td>
<td align="center">120</td>
<td align="center">SRX384353</td>
<td align="center">SRS508575</td>
<td align="center">SAMN02422682</td>
</tr>
<tr class="even">
<td align="center"><strong>SRR1039517</strong></td>
<td align="center">GSM1275871</td>
<td align="center">N080611</td>
<td align="center">trt</td>
<td align="center">untrt</td>
<td align="center">SRR1039517</td>
<td align="center">126</td>
<td align="center">SRX384354</td>
<td align="center">SRS508576</td>
<td align="center">SAMN02422673</td>
</tr>
<tr class="odd">
<td align="center"><strong>SRR1039520</strong></td>
<td align="center">GSM1275874</td>
<td align="center">N061011</td>
<td align="center">untrt</td>
<td align="center">untrt</td>
<td align="center">SRR1039520</td>
<td align="center">101</td>
<td align="center">SRX384357</td>
<td align="center">SRS508579</td>
<td align="center">SAMN02422683</td>
</tr>
<tr class="even">
<td align="center"><strong>SRR1039521</strong></td>
<td align="center">GSM1275875</td>
<td align="center">N061011</td>
<td align="center">trt</td>
<td align="center">untrt</td>
<td align="center">SRR1039521</td>
<td align="center">98</td>
<td align="center">SRX384358</td>
<td align="center">SRS508580</td>
<td align="center">SAMN02422677</td>
</tr>
</tbody>
</table></div>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Count data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assay</a></span><span class="op">(</span><span class="va">airway</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="width:100%;" class="table table-sm">
<caption>Count data for the airway experiment</caption>
<colgroup>
<col width="17%">
<col width="10%">
<col width="10%">
<col width="10%">
<col width="10%">
<col width="10%">
<col width="10%">
<col width="10%">
<col width="10%">
</colgroup>
<thead><tr class="header">
<th align="center"> </th>
<th align="center">SRR1039508</th>
<th align="center">SRR1039509</th>
<th align="center">SRR1039512</th>
<th align="center">SRR1039513</th>
<th align="center">SRR1039516</th>
<th align="center">SRR1039517</th>
<th align="center">SRR1039520</th>
<th align="center">SRR1039521</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center"><strong>ENSG00000000003</strong></td>
<td align="center">679</td>
<td align="center">448</td>
<td align="center">873</td>
<td align="center">408</td>
<td align="center">1138</td>
<td align="center">1047</td>
<td align="center">770</td>
<td align="center">572</td>
</tr>
<tr class="even">
<td align="center"><strong>ENSG00000000005</strong></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>ENSG00000000419</strong></td>
<td align="center">467</td>
<td align="center">515</td>
<td align="center">621</td>
<td align="center">365</td>
<td align="center">587</td>
<td align="center">799</td>
<td align="center">417</td>
<td align="center">508</td>
</tr>
<tr class="even">
<td align="center"><strong>ENSG00000000457</strong></td>
<td align="center">260</td>
<td align="center">211</td>
<td align="center">263</td>
<td align="center">164</td>
<td align="center">245</td>
<td align="center">331</td>
<td align="center">233</td>
<td align="center">229</td>
</tr>
<tr class="odd">
<td align="center"><strong>ENSG00000000460</strong></td>
<td align="center">60</td>
<td align="center">55</td>
<td align="center">40</td>
<td align="center">35</td>
<td align="center">78</td>
<td align="center">63</td>
<td align="center">76</td>
<td align="center">60</td>
</tr>
<tr class="even">
<td align="center"><strong>ENSG00000000938</strong></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">2</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
</tbody>
</table></div>
<p>Two questions resulting in two different formulas can be asked with this data set, on a <em>per-gene</em> basis:</p>
<ol style="list-style-type: decimal">
<li>Test for the effect of dexamethasone (the last factor), controlling for the effect of different cell line (the first factor):</li>
</ol>
<ul>
<li><code>~ cell + dex</code></li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Test whether a fold change due to treatment with dexamethasone is different across cell line using an <em>interaction term</em>:</li>
</ol>
<ul>
<li><code>~ cell + dex + cell:dex</code></li>
</ul>
<p>Using a t-test we can only ask <em>either</em> the effect of dex or the cell line and not both. Note that for this experiment the <code>paired</code> argument for a t-test should be set to <code>TRUE</code> as each cell is used in both treated and untreated conditions. Using ANOVA we will now, for a single gene, show how to get the basic statistics. This can be done in two ways; either fit a model (using <code>lm</code>) and compute the <em>analysis of variance tables</em> (using <code>anova</code>) or using the wrapper function (<code>aov</code>) that models the data using <code>lm</code> from which the statistics can be gathered using the <code>summary</code> function. First we need to determine if we have a <strong>balanced</strong> or <strong>unbalanced design</strong>, i.e. do we have equal sample sizes within the levels of our independent grouping levels (independent variables are dex and cell, the count value is the dependent variable). See the code below on how to check for a balanced design. Note that all further code for this section only uses count data for <strong>one</strong> gene (the first one).</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## First, format the data so we can use it in a formula. We need the samples as rows, </span></span>
<span><span class="co">## and the gene expression values in a single column</span></span>
<span><span class="va">dex</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">colData</a></span><span class="op">(</span><span class="va">airway</span><span class="op">)</span><span class="op">$</span><span class="va">dex</span></span>
<span><span class="va">cell</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">colData</a></span><span class="op">(</span><span class="va">airway</span><span class="op">)</span><span class="op">$</span><span class="va">cell</span></span>
<span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>count<span class="op">=</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/t.html">t</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assay</a></span><span class="op">(</span><span class="va">airway</span><span class="op">)</span><span class="op">)</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>, <span class="co"># Count data</span></span>
<span>                  <span class="va">dex</span>, <span class="va">cell</span><span class="op">)</span>                  <span class="co"># Group description</span></span>
<span></span>
<span><span class="co">## Check for design. If all values are equal, the design is balanced</span></span>
<span><span class="fu">pander</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/table.html">table</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">dex</span>, <span class="va">dat</span><span class="op">$</span><span class="va">cell</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="width:72%;" class="table table-sm">
<colgroup>
<col width="16%">
<col width="13%">
<col width="13%">
<col width="13%">
<col width="13%">
</colgroup>
<thead><tr class="header">
<th align="center"> </th>
<th align="center">N052611</th>
<th align="center">N061011</th>
<th align="center">N080611</th>
<th align="center">N61311</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center"><strong>trt</strong></td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center"><strong>untrt</strong></td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">1</td>
</tr>
</tbody>
</table></div>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">pander</span><span class="op">(</span><span class="va">dat</span>, caption <span class="op">=</span> <span class="st">"Count data for 'ENSG00000000003'"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="width:60%;" class="table table-sm">
<caption>Count data for ‘ENSG00000000003’</caption>
<colgroup>
<col width="23%">
<col width="11%">
<col width="11%">
<col width="13%">
</colgroup>
<thead><tr class="header">
<th align="center"> </th>
<th align="center">count</th>
<th align="center">dex</th>
<th align="center">cell</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center"><strong>SRR1039508</strong></td>
<td align="center">679</td>
<td align="center">untrt</td>
<td align="center">N61311</td>
</tr>
<tr class="even">
<td align="center"><strong>SRR1039509</strong></td>
<td align="center">448</td>
<td align="center">trt</td>
<td align="center">N61311</td>
</tr>
<tr class="odd">
<td align="center"><strong>SRR1039512</strong></td>
<td align="center">873</td>
<td align="center">untrt</td>
<td align="center">N052611</td>
</tr>
<tr class="even">
<td align="center"><strong>SRR1039513</strong></td>
<td align="center">408</td>
<td align="center">trt</td>
<td align="center">N052611</td>
</tr>
<tr class="odd">
<td align="center"><strong>SRR1039516</strong></td>
<td align="center">1138</td>
<td align="center">untrt</td>
<td align="center">N080611</td>
</tr>
<tr class="even">
<td align="center"><strong>SRR1039517</strong></td>
<td align="center">1047</td>
<td align="center">trt</td>
<td align="center">N080611</td>
</tr>
<tr class="odd">
<td align="center"><strong>SRR1039520</strong></td>
<td align="center">770</td>
<td align="center">untrt</td>
<td align="center">N061011</td>
</tr>
<tr class="even">
<td align="center"><strong>SRR1039521</strong></td>
<td align="center">572</td>
<td align="center">trt</td>
<td align="center">N061011</td>
</tr>
</tbody>
</table></div>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Average per treatment group</span></span>
<span><span class="fu">pander</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/tapply.html">tapply</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">count</span>, <span class="va">dat</span><span class="op">$</span><span class="va">dex</span>, <span class="va">mean</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="width:22%;" class="table table-sm">
<colgroup>
<col width="11%">
<col width="11%">
</colgroup>
<thead><tr class="header">
<th align="center">trt</th>
<th align="center">untrt</th>
</tr></thead>
<tbody><tr class="odd">
<td align="center">618.8</td>
<td align="center">865</td>
</tr></tbody>
</table></div>
<p>There is a noticable (~40%) difference in the average expression when looking at the treatment. Looking at the difference in average for the cells we see an even bigger difference.</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">pander</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/tapply.html">tapply</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">count</span>, <span class="va">dat</span><span class="op">$</span><span class="va">cell</span>, <span class="va">mean</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="width:56%;" class="table table-sm">
<colgroup>
<col width="13%">
<col width="13%">
<col width="13%">
<col width="13%">
</colgroup>
<thead><tr class="header">
<th align="center">N052611</th>
<th align="center">N061011</th>
<th align="center">N080611</th>
<th align="center">N61311</th>
</tr></thead>
<tbody><tr class="odd">
<td align="center">640.5</td>
<td align="center">671</td>
<td align="center">1092</td>
<td align="center">563.5</td>
</tr></tbody>
</table></div>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Create a model for the first question listed above</span></span>
<span><span class="co">## By using two independent variables, this is a TWO-way ANOVA</span></span>
<span><span class="va">model.airway</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">count</span> <span class="op">~</span> <span class="va">cell</span> <span class="op">+</span> <span class="va">dex</span>, data<span class="op">=</span><span class="va">dat</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Alternative method, same result:</span></span>
<span><span class="co"># summary( aov(count ~ cell + dex, data=dat) )</span></span>
<span></span>
<span><span class="co">## Print the analysis of variance table</span></span>
<span><span class="fu">pander</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">model.airway</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table style="width:83%;" class="table table-sm">
<caption>Analysis of Variance Table
For this gene, both the treatment <em>and</em> the cell have an <em>almost</em> significant p-value (<code>Pr(&gt;F)</code> &lt; 0.05). With the treatment having only two options we can simply state that the treatment shows <em>some</em> effect, but we have to accept the <span class="math inline">\(H_0\)</span> hypothesis (all means are equal) since <span class="math inline">\(\alpha\)</span> &gt; 0.05. Let’s assume for now that we found a gene with an <span class="math inline">\(\alpha\)</span> &lt; 0.05 where we reject <span class="math inline">\(H_0\)</span>. With there being 4 different cell sources, we can only say that <em>at least one cell-type shows an effect</em>. To find out exactly <em>which</em> of the cell sources that is requires multiple t-tests (<span class="math inline">\(R = 1/2k(k-1)=6\)</span> separate tests comparing all groups). Alternatively, the <code>pairwise.t.test</code> function can be used for this.</caption>
<colgroup>
<col width="22%">
<col width="6%">
<col width="12%">
<col width="13%">
<col width="13%">
<col width="13%">
</colgroup>
<thead><tr class="header">
<th align="center"> </th>
<th align="center">Df</th>
<th align="center">Sum Sq</th>
<th align="center">Mean Sq</th>
<th align="center">F value</th>
<th align="center">Pr(&gt;F)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center"><strong>cell</strong></td>
<td align="center">3</td>
<td align="center">340111</td>
<td align="center">113370</td>
<td align="center">9.129</td>
<td align="center">0.05108</td>
</tr>
<tr class="even">
<td align="center"><strong>dex</strong></td>
<td align="center">1</td>
<td align="center">121278</td>
<td align="center">121278</td>
<td align="center">9.765</td>
<td align="center">0.05227</td>
</tr>
<tr class="odd">
<td align="center"><strong>Residuals</strong></td>
<td align="center">3</td>
<td align="center">37257</td>
<td align="center">12419</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
</tbody>
</table></div>
<p>After performing ANOVA some steps should be performed to check if the results are viable, tests like the <strong>Levene’s test</strong> for checking the homogeneity of variances and checking for <strong>normality</strong> of the residuals. While this is a technical solution and fully understanding falls outside of the scope of this course, a simple plot can be made (not for all genes/ tests) to see if the residuals are normally distributed. We expect the datapoints to approximately follow a straight diagonal line. Samples that differ too much are annotated in the plot and can be reason for concern.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Plotting the full model (remove the 2) shows other statistics as well</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">model.airway</span>, <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<img src="gene_expression_files/figure-html/anovePlot,%20anova-residuals-normality-1.png" alt="ANOVA model plot" width="672"><p class="caption">
(#fig:anovePlot, anova-residuals-normality)ANOVA model plot
</p>
</div>
<p><em>ANOVA</em> tutorials</p>
<ul>
<li><a href="https://bioinf.nl/~michiel/courses/R_minor/ttest.html#anova">M. A. Noback, DAVuR Course Syllabus</a></li>
<li><a href="http://www.statmethods.net/stats/anova.html">Quick-R @ statmethods</a></li>
<li><a href="http://www.r-bloggers.com/one-way-analysis-of-variance-anova/">R-bloggers</a></li>
<li><a href="http://www.sthda.com/english/wiki/two-way-anova-test-in-r">Statistical tools for high-throughput data analysis</a></li>
</ul>
</div>
</div>
<div id="deg-mtc" class="section level2" number="4.4">
<h2>
<span class="header-section-number">4.4</span> Multiple Testing Correction<a class="anchor" aria-label="anchor" href="#deg-mtc"><i class="fas fa-link"></i></a>
</h2>
<p>Read the text about <strong>Multiple comparisons</strong> at the <a href="http://www.biostathandbook.com/multiplecomparisons.html">biostathandbook</a> and the help of the <code>p.adjust R</code> function. Your article is a possible source to see which correction method they applied. If this is not mentioned there it is probably best to use the <code>fdr</code> (also called the <code>Benjamini Hochberg</code>) method.</p>
<div class="rmdtip">
<p>
An expected side-effect of correcting for multiple-testing is the
lower number of genes with a resulting p-value &lt; 0.05 (caused by
hopefuly removing false-positives). For example, using a p-value of 0.05
<em>expects</em> 5% of all tests to result in false-positives. Thus when
testing &gt;20.000 genes it is expected that 1000 tests are in fact a
false-positive. In some cases though, you end up with <strong>0</strong>
genes that have a low p-value and thus you have no DEGs. Using the
<em>Bonferroni</em> correction for instance, multiplies the p-values by
the number of comparisons. With 20.000 comparisons, a p-value must be
&lt;= 0.0025 to ‘survive’ the correction and still be &lt; 0.05. One
‘solution’ is to increase the alpha-value from 0.05 to 0.1, this is also
often found in articles where DEGs are determined with a
<em>combination</em> of p-value &lt; 0.05 <strong>and</strong>
p-adjusted &lt; 0.1.
</p>
</div>
<div id="inspecting-manual-test-results" class="section level3" number="4.4.1">
<h3>
<span class="header-section-number">4.4.1</span> Inspecting Manual Test Results<a class="anchor" aria-label="anchor" href="#inspecting-manual-test-results"><i class="fas fa-link"></i></a>
</h3>
<p>After applying a form of multiple testing correction, you end up with two p-values for <em>each</em> gene in your data set. DEGs can then be filtered out using simple R commands looking for adjusted p-values &lt; 0.05 and optionally a threshold log-FC value. The resulting set of genes show a statistically significant difference between the sample groups that were used in the test(s) and these can be used to answer any relevant biological question. For now, keep the results as we will inspect them closer in <a href="chapter-5.html#chapter-5">chapter 5; Data Analysis</a>.</p>
</div>
</div>
<div id="deg-bioconductor" class="section level2" number="4.5">
<h2>
<span class="header-section-number">4.5</span> Using Bioconductor Packages<a class="anchor" aria-label="anchor" href="#deg-bioconductor"><i class="fas fa-link"></i></a>
</h2>
<p>This section demonstrates the use of two packages to perform DEG-analysis on <strong>count</strong> data. There are many packages available on Bioconductor for similar analysis, such as <code>DSS</code>, <code>EBSeq</code>, <code>NOISeq</code> and <code>BaySeq</code>, but here we will focus on <code>edgeR</code> and <code>DESeq2</code> for processing count-based data. Chances are that either of these two packages are mentioned if the article described the use of R for the statistical analysis as they are the most widely accepted methods of processing gene expression data.</p>
<p>Both packages apply their own normalization methods (described in the sections below) therefore they only work on the <strong>raw</strong> count data. If your data consists of <strong>expected</strong> count data, you need to round these values down (using the <code>floor</code> function). You can choose one of these two packages to use, or use them both since it could increase statistical power and they are not very hard to use once you understand how to <strong>model</strong> the data as we’ll show next.</p>
<ul>
<li>
<strong>Assignment</strong>: Perform data-analysis using at least one of the two packages. If possible, use both of them so we can compare the results between the manual-testing results and both packages.
<ul>
<li>Start by documenting the relevant information from the article, also if they used other software for this analysis.</li>
</ul>
</li>
</ul>
<div class="rmdtip">
The two listed packages come with a very complete and extensive manual. These manuals can be found as PDF on the BioConductor website, or opened from within R using the <code>vignette</code> function. To see all available manuals (note; these are very different from the function-help documentation) execute the function without arguments: <code><a href="https://rdrr.io/r/utils/vignette.html">vignette()</a></code>. This lists the vignettes for edgeR and DESeq2 as:
* <code><a href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html">vignette("DESeq2")</a></code> (this whole course is partly designed on this document!)
* <code>vignette("edgeR")</code>
</div>
<div id="deg-design" class="section level3" number="4.5.1">
<h3>
<span class="header-section-number">4.5.1</span> The <code>Design</code> (matrix)<a class="anchor" aria-label="anchor" href="#deg-design"><i class="fas fa-link"></i></a>
</h3>
<p>For all of these packages you need to properly specify <em>how</em> your samples are grouped. We have seen examples of this using an <code>R factor</code> object with the heatmap, MDS and PCA visualizations to tell which groups of samples we have and to which group each sample belongs. Reading the documentation for the below packages shows that this is an important part of performing DE-analysis. For example, the following code is shown in de <code>edgeR</code> documentation on page 8 where two sample groups are defined (numbered <code>1</code> and <code>2</code>), placed in a <code>factor</code> object and used as input in the <code>model.matrix</code> function.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">group</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>, <span class="st">"Case"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">(</span><span class="va">design</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span> <span class="op">~</span> <span class="va">group</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   (Intercept) groupCase
## 1           1         0
## 2           1         0
## 3           1         1
## 4           1         1
## attr(,"assign")
## [1] 0 1
## attr(,"contrasts")
## attr(,"contrasts")$group
## [1] "contr.treatment"</code></pre>
<p>As mentioned before we <strong>need</strong> to think about the <em>question</em> we want to aks; which difference do we want to know? With two sample groups as used here the question is rather easy; ‘which genes show an effect between case/ control samples?’. With more then two sample groups however the question becomes more difficult. If we have an experiment comparing influence of three kinds of drugs (thus three groups) <em>combined</em> with effect over time, do we then want to focus on the influence of the <em>drugs</em> or the <em>time</em>? Both are valid questions but they define the way of how to create the <code>design matrix</code>.</p>
<p>Documentation on this subject is plenty, however it often contains overwhelming information. <a href="http://genomicsclass.github.io/book/pages/expressing_design_formula.html">This page</a> contains some valuable details (you can safely start reading at <strong>Choice of design</strong>), including the following text which is based on the same example used in the <code>edgeR</code> documentation:</p>
<blockquote>
<p>“For the examples we cover here, we use linear models to make comparisons between different groups. Hence, the design matrices that we ultimately work with will have at least two columns: an intercept column, which consists of a column of 1’s, and a second column, which specifies which samples are in a second group. In this case, two coefficients are fit in the linear model: the intercept, which represents the population average of the first group, and a second coefficient, which represents the difference between the population averages of the second group and the first group. The latter is typically the coefficient we are interested in when we are performing statistical tests: we want to know if their is a difference between the two groups.”</p>
</blockquote>
<p>If you have more then two sample groups and you want to change the <em>question</em> (i.e. test the influence of a different group), read the section about <strong>Releveling</strong> the <code>factor</code>.</p>
</div>
<div id="deg-deseq2" class="section level3" number="4.5.2">
<h3>
<span class="header-section-number">4.5.2</span> <code>DESeq2</code><a class="anchor" aria-label="anchor" href="#deg-deseq2"><i class="fas fa-link"></i></a>
</h3>
<p>We have used the <code>DESeq2</code> library before and for DEG analysis we could re-use the <code>DESeqDataSet</code> object but it is adviced to create a new object with the proper design formula instead of the <code>~ 1</code> we used before.</p>
<p>There is no need to normalize the data using the previously used <code>rlog</code> function because the <code>DESeq2</code> library will normalize the count data for you as follows:</p>
<blockquote>
<p>“DESeq computes a scaling factor for a given sample by computing the median of the ratio, for each gene, of its read count over its geometric mean across all samples. It then uses the assumption that most genes are not DE and uses this median of ratios to obtain the scaling factor associated with this sample.”</p>
</blockquote>
<p>For our example data with four sample groups we re-use the annotation dataframe as created in the <a href="chapter-3.html#eda_heatmap">EDA: Heatmap</a> section (printed below). This allows us to do comparisons based on the celltype and ploidy of the samples. One minor note of importance is that the first level in each factor is taken as the <em>reference</em>, or for expression analysis, the <em>control</em> group. In our example (see the table below) the IPSC is the control-celltype and disomic the control-ploidy. In a simple case/ control study, the first level (check with the <code><a href="https://rdrr.io/pkg/S4Vectors/man/Factor-class.html">levels()</a></code> function) should be the control group. Use the <code><a href="https://rdrr.io/r/stats/relevel.html">relevel()</a></code> function if the levels need to be switched.</p>
<div class="inline-table"><table style="width:53%;" class="table table-sm">
<colgroup>
<col width="25%">
<col width="12%">
<col width="15%">
</colgroup>
<thead><tr class="header">
<th align="center"> </th>
<th align="center">Cell</th>
<th align="center">Ploidy</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center"><strong>di_IPSC_r1</strong></td>
<td align="center">IPSC</td>
<td align="center">disomic</td>
</tr>
<tr class="even">
<td align="center"><strong>di_IPSC_r2</strong></td>
<td align="center">IPSC</td>
<td align="center">disomic</td>
</tr>
<tr class="odd">
<td align="center"><strong>di_IPSC_r3</strong></td>
<td align="center">IPSC</td>
<td align="center">disomic</td>
</tr>
<tr class="even">
<td align="center"><strong>tri_IPSC_r1</strong></td>
<td align="center">IPSC</td>
<td align="center">trisomic</td>
</tr>
<tr class="odd">
<td align="center"><strong>tri_IPSC_r2</strong></td>
<td align="center">IPSC</td>
<td align="center">trisomic</td>
</tr>
<tr class="even">
<td align="center"><strong>tri_IPSC_r3</strong></td>
<td align="center">IPSC</td>
<td align="center">trisomic</td>
</tr>
<tr class="odd">
<td align="center"><strong>di_NEUR_r1</strong></td>
<td align="center">Neuron</td>
<td align="center">disomic</td>
</tr>
<tr class="even">
<td align="center"><strong>di_NEUR_r2</strong></td>
<td align="center">Neuron</td>
<td align="center">disomic</td>
</tr>
<tr class="odd">
<td align="center"><strong>di_NEUR_r3</strong></td>
<td align="center">Neuron</td>
<td align="center">disomic</td>
</tr>
<tr class="even">
<td align="center"><strong>tri_NEUR_r1</strong></td>
<td align="center">Neuron</td>
<td align="center">trisomic</td>
</tr>
<tr class="odd">
<td align="center"><strong>tri_NEUR_r2</strong></td>
<td align="center">Neuron</td>
<td align="center">trisomic</td>
</tr>
<tr class="even">
<td align="center"><strong>tri_NEUR_r3</strong></td>
<td align="center">Neuron</td>
<td align="center">trisomic</td>
</tr>
</tbody>
</table></div>
<p>Once you have a proper <code>DESeqDataSet</code> all you need to do is run the <code>DESeq</code> function on this object. Then, using the <code>results</code> function you can extract the DEGs as a <code>DESeqResults</code> object. Applying the <code>summary</code> function on these object(s) shows the number of up and down regulated DEGs as can be seen below that lists the impact of trisomy for the IPSC cell type (~800 DEGs) and comparing both the IPSC and Neuron disomic (control) cell types (as can be seen, a <em>huge</em> amount of genes are affected by differentiation from stem cell into cortical neurons):</p>
<div class="inline-table"><table class="container">
<tr>
<th align="center">
IPSC - Trisomic vs Disomic
</th>
<th align="center">
Disomic Neuron vs Disomic IPSC
</th>
</tr>
<tr>
<td>
<pre>
out of 44504 with nonzero total read count
adjusted p-value &lt; 0.05
LFC &gt; 0 (up)       : 432, 0.97%
LFC &lt; 0 (down)     : 417, 0.94%
outliers [1]       : 219, 0.49%
low counts [2]     : 17004, 38%
(mean count &lt; 6)
[1] see 'cooksCutoff' argument of ?results
[2] see 'independentFiltering' argument of ?results

</pre>
</td>
<td>
<pre>
out of 44504 with nonzero total read count
adjusted p-value &lt; 0.05
LFC &gt; 0 (up)       : 9594, 22%
LFC &lt; 0 (down)     : 8224, 18%
outliers [1]       : 219, 0.49%
low counts [2]     : 11906, 27%
(mean count &lt; 2)
[1] see 'cooksCutoff' argument of ?results
[2] see 'independentFiltering' argument of ?results

</pre>
</td>
</tr>
</table></div>
<p>The output of the <code>results</code> function contains the following columns for each gene:</p>
<div class="inline-table"><table style="width:89%;" class="table table-sm">
<colgroup>
<col width="23%">
<col width="20%">
<col width="44%">
</colgroup>
<thead><tr class="header">
<th align="center">Column</th>
<th align="center">Type</th>
<th align="center">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">baseMean</td>
<td align="center">intermediate</td>
<td align="center">mean of normalized counts for
all samples</td>
</tr>
<tr class="even">
<td align="center">log2FoldChange</td>
<td align="center">results</td>
<td align="center">log2 fold change (MLE): group
IPSC.trisomic vs IPSC.disomic</td>
</tr>
<tr class="odd">
<td align="center">lfcSE</td>
<td align="center">results</td>
<td align="center">standard error: group
IPSC.trisomic vs IPSC.disomic</td>
</tr>
<tr class="even">
<td align="center">stat</td>
<td align="center">results</td>
<td align="center">Wald statistic: group
IPSC.trisomic vs IPSC.disomic</td>
</tr>
<tr class="odd">
<td align="center">pvalue</td>
<td align="center">results</td>
<td align="center">Wald test p-value: group
IPSC.trisomic vs IPSC.disomic</td>
</tr>
<tr class="even">
<td align="center">padj</td>
<td align="center">results</td>
<td align="center">BH adjusted p-values</td>
</tr>
</tbody>
</table></div>
<p><em>How</em> you call the <code>results</code> function depends heavily on your experiment. As you can see from the output of the <code>summary</code> function, there are no details given about <em>which</em> comparison is shown (and also, by default a p-value of 0.1 is used instead of 0.05).</p>
<p>Depending on the <em>design</em> used to create the <code>DESeqDataSet</code> with, one or more comparisons can be made (applying the <code>DESeq</code> function calculates all and you filter with the <code>results</code> function). Read the help for the <code>results</code> function carefully; especially regarding the <code>contrast</code> argument where you define the comparison to retrieve. The following code can be used for our example experiment to get the DEGs comparing the celltypes using an adjusted p-value of 0.05:</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DESeq2/man/results.html">results</a></span><span class="op">(</span><span class="va">dds</span>, contrast <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Cell"</span>, <span class="st">"IPSC"</span>, <span class="st">"Neuron"</span><span class="op">)</span>,</span>
<span>               alpha <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span></span></code></pre></div>
<p>The <code>DESeq2</code> library contains a number of plotting functions that can be applied to a <code>DESeqResults</code> object (output of the <code>results</code> function), the most notable is the <code>plotMA</code> function. Note that the first MA-plot shown below has a very high range for the log fold changes (-10, 10) where the maximum value is 22.4 (shown as a triangle stating it is outside of the plotting range). A <strong>log</strong> fold change of 22 means &gt;5 <em>million</em> increased expression which seems artificially high. DESeq2 includes a function to perform downstream processing of the estimated log fold change values called <code>lfcShrink</code> which is adviced to always run afterwards. The reason for executing this function is described in the vignette with:</p>
<blockquote>
<p>“It is more useful visualize the MA-plot for the shrunken log2 fold changes, which remove the noise associated with log2 fold changes from low count genes without requiring arbitrary filtering thresholds.”</p>
</blockquote>
<div class="figure">
<span style="display:block;" id="fig:DESeq2MAPlot"></span>
<img src="chapters/images/DESeq2MAplot.png" alt="MA-plots with the standard DESeq2 output (left) and after shrinking with 'lfcShrink' (right)"><p class="caption">
Figure 4.1: MA-plots with the standard DESeq2 output (left) and after shrinking with ‘lfcShrink’ (right)
</p>
</div>
<p><strong>Links</strong></p>
<ul>
<li>
<a href="https://www.bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html">Analyzing RNA-seq data with DESeq2</a> A <em>very</em> comprehensive guide to analyzing RNA-Seq data using DESeq2 (part of this document has been used in this material too!). It is adviced to read the first few sections of this guide and take a good look at the index of the document because there are many interesting sections that might be of help later.</li>
<li>
<a href="https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0550-8">Publication</a>, an accompanying article showing differences in performance compared to other methods and packages.</li>
</ul>
</div>
<div id="deg-edger" class="section level3" number="4.5.3">
<h3>
<span class="header-section-number">4.5.3</span> <code>edgeR</code><a class="anchor" aria-label="anchor" href="#deg-edger"><i class="fas fa-link"></i></a>
</h3>
<p>One of the most mature libraries for RNA-Seq data analysis is the <code>edgeR</code> library available on <a href="http://bioconductor.org/packages/release/bioc/html/edgeR.html">Bioconductor</a>. There is a very complete (sometimes a bit complex) manual available of which you need to read <a href="https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf">Chapter 2</a> with a focus on 2.1 to 2.7, 2.9 and - if you have a more complex design - 2.10. Section 1.4 (Quickstart) shows a code example on the steps needed to do DEG analysis using count data using the two <code>glm</code> methods (<em>quasi-likelihood F-tests</em> and <em>likelihood ratio tests</em>). All the steps shown there are identical for the non-<code>glm</code> method up to calculating the <code>fit</code> object which can be replaced by performing the <code>exactTest</code> function as shown in section 2.9.2.</p>
<p>The <code>edgeR</code> library will normalize the count data for you as follows:</p>
<blockquote>
<p>“The trimmed means of M values (TMM) from Robinson and Oshlack, which is implemented in edgeR, computes a scaling factor between two experiments by using the weighted average of the subset of genes after excluding genes that exhibit high average read counts and genes that have large differences in expression.”</p>
</blockquote>
<p>Running edgeR requires the raw count data together with the grouping-factor packaged in a <code>DGEList</code> object (with the <code>DGEList()</code> function). Furthermore, a proper <code>model.matrix</code> object (see the section on <a href="chapter-4.html#deg-design">design</a>) is needed as input for the <code>estimateDisp</code> function. The exact steps to take (there are more variations than with DESeq2) must be searched in the documentation linked above.</p>
<p>Once the analysis is done you can retrieve the actual results with the <code>topTags</code> function:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="19%">
<col width="14%">
<col width="11%">
<col width="11%">
<col width="10%">
<col width="15%">
<col width="15%">
</colgroup>
<thead><tr class="header">
<th align="center"> </th>
<th align="center">genes</th>
<th align="center">logFC</th>
<th align="center">logCPM</th>
<th align="center">F</th>
<th align="center">PValue</th>
<th align="center">FDR</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center"><strong>PCDHA10</strong></td>
<td align="center">PCDHA10</td>
<td align="center">-3.605</td>
<td align="center">5.676</td>
<td align="center">445.2</td>
<td align="center">1.343e-10</td>
<td align="center">2.227e-06</td>
</tr>
<tr class="even">
<td align="center"><strong>CHGA</strong></td>
<td align="center">CHGA</td>
<td align="center">2.923</td>
<td align="center">5.976</td>
<td align="center">184.7</td>
<td align="center">1.801e-08</td>
<td align="center">0.0001494</td>
</tr>
<tr class="odd">
<td align="center"><strong>TSSC2</strong></td>
<td align="center">TSSC2</td>
<td align="center">3.176</td>
<td align="center">3.301</td>
<td align="center">164.7</td>
<td align="center">3.372e-08</td>
<td align="center">0.0001716</td>
</tr>
<tr class="even">
<td align="center"><strong>ARRB1</strong></td>
<td align="center">ARRB1</td>
<td align="center">-3.911</td>
<td align="center">5.015</td>
<td align="center">158.6</td>
<td align="center">4.137e-08</td>
<td align="center">0.0001716</td>
</tr>
<tr class="odd">
<td align="center"><strong>LRFN5</strong></td>
<td align="center">LRFN5</td>
<td align="center">-4.627</td>
<td align="center">4.118</td>
<td align="center">146.2</td>
<td align="center">6.423e-08</td>
<td align="center">0.0002094</td>
</tr>
<tr class="even">
<td align="center"><strong>MAP2</strong></td>
<td align="center">MAP2</td>
<td align="center">2.649</td>
<td align="center">9.468</td>
<td align="center">140.6</td>
<td align="center">7.932e-08</td>
<td align="center">0.0002094</td>
</tr>
<tr class="odd">
<td align="center"><strong>C11orf54</strong></td>
<td align="center">C11orf54</td>
<td align="center">-1.953</td>
<td align="center">4.915</td>
<td align="center">137.8</td>
<td align="center">8.837e-08</td>
<td align="center">0.0002094</td>
</tr>
<tr class="even">
<td align="center"><strong>WNT3</strong></td>
<td align="center">WNT3</td>
<td align="center">-3.487</td>
<td align="center">3.273</td>
<td align="center">107.9</td>
<td align="center">3.248e-07</td>
<td align="center">0.0006735</td>
</tr>
<tr class="odd">
<td align="center"><strong>TFAP2C</strong></td>
<td align="center">TFAP2C</td>
<td align="center">-2.98</td>
<td align="center">4.591</td>
<td align="center">99.22</td>
<td align="center">5.042e-07</td>
<td align="center">0.0009292</td>
</tr>
<tr class="even">
<td align="center"><strong>PITPNM2</strong></td>
<td align="center">PITPNM2</td>
<td align="center">-2.669</td>
<td align="center">3.968</td>
<td align="center">96.37</td>
<td align="center">5.868e-07</td>
<td align="center">0.0009734</td>
</tr>
</tbody>
</table></div>
<p>Most significant genes given by edgeR</p>
<p>The package also contains a few plotting methods that you can use at intermediate steps during the analysis. For instance, after calculating the normalization factors (<code>calcNormFactors</code>), you can perform multi-dimensional scaling with the <code>plotMDS</code> function which is similar to what we’ve done manually in chapter three:</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">plotMDS</span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:edgeRPlotMDS"></span>
<img src="gene_expression_files/figure-html/edgeRPlotMDS-1.png" alt="edgeR MDS plot based on the calculated log2 fold changes" width="672"><p class="caption">
Figure 4.2: edgeR MDS plot based on the calculated log2 fold changes
</p>
</div>
<p>Or the <em>dispersion</em> after running the <code>estimateDisp</code> function with the <code>plotBCV</code> function:</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">plotBCV</span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:edgeRPlotBCV"></span>
<img src="gene_expression_files/figure-html/edgeRPlotBCV-1.png" alt="edgeR plot of several dispersion methods" width="672"><p class="caption">
Figure 4.3: edgeR plot of several dispersion methods
</p>
</div>
<p>Or the log-fold changes for all genes, once we have the output of the <code>exactTest</code> function (output <code>et</code> is an <code>DGEExact</code> object) with the <code>plotSmear</code> function. The <code>abline</code> shows a log-FC threshold:</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">deGenes</span> <span class="op">&lt;-</span> <span class="fu">decideTests.DGEExact</span><span class="op">(</span><span class="va">qlf</span>, p<span class="op">=</span><span class="fl">0.05</span><span class="op">)</span></span>
<span><span class="va">deGenes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html">rownames</a></span><span class="op">(</span><span class="va">qlf</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/logical.html">as.logical</a></span><span class="op">(</span><span class="va">deGenes</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="fu">plotSmear</span><span class="op">(</span><span class="va">qlf</span>, de.tags<span class="op">=</span><span class="va">deGenes</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>h<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>, col<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:edgerResults"></span>
<img src="gene_expression_files/figure-html/edgerResults-1.png" alt="edgeR results; genes marked in red are DEGs" width="672"><p class="caption">
Figure 4.4: edgeR results; genes marked in red are DEGs
</p>
</div>
<p><strong>Links</strong></p>
<ul>
<li>
<a href="http://bioinformatics-core-shared-training.github.io/cruk-bioinf-sschool/Day3/rnaSeq_DE.pdf">Differential Expression Analysis using edgeR</a> tutorial</li>
<li>
<a href="https://gist.github.com/jdblischak/11384914">Another tutorial</a> hosted on GitHub</li>
</ul>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="chapter-3.html"><span class="header-section-number">3</span> Exploratory Data Analysis</a></div>
<div class="next"><a href="chapter-5.html"><span class="header-section-number">5</span> Data Analysis and Visualization</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#chapter-4"><span class="header-section-number">4</span> Discovering Differentialy Expressed Genes (DEGs)</a></li>
<li><a class="nav-link" href="#deg-preprocessing"><span class="header-section-number">4.1</span> Pre-processing</a></li>
<li><a class="nav-link" href="#deg-fc"><span class="header-section-number">4.2</span> The Fold Change Value</a></li>
<li>
<a class="nav-link" href="#deg-manual"><span class="header-section-number">4.3</span> Using Manual Methods (t-test &amp; ANOVA)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#deg-ttest"><span class="header-section-number">4.3.1</span> Students T-test</a></li>
<li><a class="nav-link" href="#deg-anova"><span class="header-section-number">4.3.2</span> Analysis of Variance (ANOVA)</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#deg-mtc"><span class="header-section-number">4.4</span> Multiple Testing Correction</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#inspecting-manual-test-results"><span class="header-section-number">4.4.1</span> Inspecting Manual Test Results</a></li></ul>
</li>
<li>
<a class="nav-link" href="#deg-bioconductor"><span class="header-section-number">4.5</span> Using Bioconductor Packages</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#deg-design"><span class="header-section-number">4.5.1</span> The Design (matrix)</a></li>
<li><a class="nav-link" href="#deg-deseq2"><span class="header-section-number">4.5.2</span> DESeq2</a></li>
<li><a class="nav-link" href="#deg-edger"><span class="header-section-number">4.5.3</span> edgeR</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Transcriptomics Project - Gene Expression Analysis</strong>" was written by Marcel Kempenaar. It was last built on 2026-04-19.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
