<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content=" Exploratory Data Analysis | 2.1.2 Genomics &amp; Transcriptomics" />
<meta property="og:type" content="book" />

<meta property="og:description" content="Course Syllabus for course 2.1.2" />
<meta name="github-repo" content="mkempenaar/gene_expression_analysis" />

<meta name="author" content="Marcel Kempenaar" />

<meta name="date" content="2025-04-25" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="Course Syllabus for course 2.1.2">

<title> Exploratory Data Analysis | 2.1.2 Genomics &amp; Transcriptomics</title>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
/* show arrow before summary tag as in bootstrap
TODO: remove if bootstrap in updated in html_document (rmarkdown#1485) */
details > summary {
  display: list-item;
  cursor: pointer;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li class="has-sub"><a href="index.html#chapter-1" id="toc-chapter-1"><span class="toc-section-number">1</span> Introduction</a>
<ul>
<li class="has-sub"><a href="index.html#genomics" id="toc-genomics"><span class="toc-section-number">1.1</span> 2.1.2 Genomics</a>
<ul>
<li><a href="index.html#project-deliverables" id="toc-project-deliverables"><span class="toc-section-number">1.1.1</span> Project Deliverables</a></li>
<li><a href="index.html#data-processing" id="toc-data-processing"><span class="toc-section-number">1.1.2</span> Data Processing</a></li>
<li><a href="index.html#finding-a-data-set" id="toc-finding-a-data-set"><span class="toc-section-number">1.1.3</span> Finding a Data Set</a></li>
</ul></li>
<li class="has-sub"><a href="index.html#transcriptomics" id="toc-transcriptomics"><span class="toc-section-number">1.2</span> 2.1.2 Transcriptomics</a>
<ul>
<li><a href="index.html#project-deliverables-1" id="toc-project-deliverables-1"><span class="toc-section-number">1.2.1</span> Project Deliverables</a></li>
</ul></li>
<li><a href="index.html#lab-journal" id="toc-lab-journal"><span class="toc-section-number">1.3</span> <em>Lab Journal</em></a></li>
<li class="has-sub"><a href="index.html#schedule" id="toc-schedule"><span class="toc-section-number">1.4</span> Schedule</a>
<ul>
<li><a href="index.html#genomics-1" id="toc-genomics-1"><span class="toc-section-number">1.4.1</span> Genomics</a></li>
<li><a href="index.html#transcriptomics-1" id="toc-transcriptomics-1"><span class="toc-section-number">1.4.2</span> Transcriptomics</a></li>
</ul></li>
<li><a href="index.html#literature" id="toc-literature"><span class="toc-section-number">1.5</span> Literature</a></li>
</ul></li>
<li class="has-sub"><a href="from-reads-to-counts.html#from-reads-to-counts" id="toc-from-reads-to-counts"><span class="toc-section-number">2</span> From Reads to Counts</a>
<ul>
<li><a href="from-reads-to-counts.html#downloading-and-extracting-fastq-files" id="toc-downloading-and-extracting-fastq-files"><span class="toc-section-number">2.1</span> Downloading and extracting FastQ files</a></li>
<li><a href="from-reads-to-counts.html#optional-annotation" id="toc-optional-annotation"><span class="toc-section-number">2.2</span> (Optional) Annotation</a></li>
<li class="has-sub"><a href="from-reads-to-counts.html#quality-control" id="toc-quality-control"><span class="toc-section-number">2.3</span> Quality Control</a>
<ul>
<li><a href="from-reads-to-counts.html#fastqc" id="toc-fastqc"><span class="toc-section-number">2.3.1</span> FastQC</a></li>
</ul></li>
<li><a href="from-reads-to-counts.html#trimming" id="toc-trimming"><span class="toc-section-number">2.4</span> Trimming</a></li>
<li class="has-sub"><a href="from-reads-to-counts.html#mapping-with-star" id="toc-mapping-with-star"><span class="toc-section-number">2.5</span> Mapping with STAR</a>
<ul>
<li><a href="from-reads-to-counts.html#building-star-index" id="toc-building-star-index"><span class="toc-section-number">2.5.1</span> Building STAR index</a></li>
<li><a href="from-reads-to-counts.html#read-mapping-and-transcript-counting" id="toc-read-mapping-and-transcript-counting"><span class="toc-section-number">2.5.2</span> Read mapping and transcript counting</a></li>
<li><a href="from-reads-to-counts.html#combining-star-count-files" id="toc-combining-star-count-files"><span class="toc-section-number">2.5.3</span> Combining STAR Count Files</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="EDA.html#EDA" id="toc-EDA"><span class="toc-section-number">3</span> Exploratory Data Analysis</a>
<ul>
<li><a href="EDA.html#loading-data" id="toc-loading-data"><span class="toc-section-number">3.1</span> Loading data into R</a></li>
<li><a href="EDA.html#ch3_example_data" id="toc-ch3_example_data"><span class="toc-section-number">3.2</span> Example Data</a></li>
<li class="has-sub"><a href="EDA.html#EDA_part1" id="toc-EDA_part1"><span class="toc-section-number">3.3</span> Visualizing using <code>boxplot</code> and <code>density plot</code></a>
<ul>
<li><a href="EDA.html#eda_statistics" id="toc-eda_statistics"><span class="toc-section-number">3.3.1</span> Statistics</a></li>
<li><a href="EDA.html#eda_boxplots" id="toc-eda_boxplots"><span class="toc-section-number">3.3.2</span> Boxplots</a></li>
<li><a href="EDA.html#eda_density_plot" id="toc-eda_density_plot"><span class="toc-section-number">3.3.3</span> Density Plots</a></li>
</ul></li>
<li class="has-sub"><a href="EDA.html#EDA_part2" id="toc-EDA_part2"><span class="toc-section-number">3.4</span> Visualizing using <code>heatmap</code> and <code>MDS</code></a>
<ul>
<li><a href="EDA.html#normalization" id="toc-normalization"><span class="toc-section-number">3.4.1</span> Normalization</a></li>
<li><a href="EDA.html#eda_distance" id="toc-eda_distance"><span class="toc-section-number">3.4.2</span> Distance Calculation</a></li>
<li><a href="EDA.html#eda_heatmap" id="toc-eda_heatmap"><span class="toc-section-number">3.4.3</span> Sample Distances using a Heatmap</a></li>
<li><a href="EDA.html#eda_mds" id="toc-eda_mds"><span class="toc-section-number">3.4.4</span> Multi-Dimensional Scaling</a></li>
</ul></li>
<li><a href="EDA.html#cleaning-data" id="toc-cleaning-data"><span class="toc-section-number">3.5</span> Cleaning Data</a></li>
</ul></li>
<li class="has-sub"><a href="chapter-4.html#chapter-4" id="toc-chapter-4"><span class="toc-section-number">4</span> Discovering Differentialy Expressed Genes (DEGs)</a>
<ul>
<li><a href="chapter-4.html#deg-preprocessing" id="toc-deg-preprocessing"><span class="toc-section-number">4.1</span> Pre-processing</a></li>
<li><a href="chapter-4.html#deg-fc" id="toc-deg-fc"><span class="toc-section-number">4.2</span> The <em>Fold Change</em> Value</a></li>
<li><a href="chapter-4.html#deg-bioconductor" id="toc-deg-bioconductor"><span class="toc-section-number">4.3</span> Using Bioconductor Packages</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="EDA" class="section level1" number="3">
<h1><span class="header-section-number"></span> Exploratory Data Analysis</h1>
<p>We start with performing some exploratory data analysis steps with the goal of getting to grips with your chosen data set to properly identify a strategy for the actual analysis steps. During this exploration we will also keep an eye on the quality of the data. Even though the downloadable data is ‘processed’, there might be samples present that deviate too much from the other group of samples (a so called <em>outlier</em>). Creating basic visualizations of the data will give the necessary insight before we continue.</p>
<div id="loading-data" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Loading data into R</h2>
<p>Once you have one or more column based text files they can be read into R simply by using the <code>read.table()</code> function.</p>
<p>Follow the following steps to read in the data and start the exploratory data analysis. The resulting document should be treated as a lab journal where you log the process from loading the data to the final analysis steps.</p>
<ul>
<li>Open RStudio</li>
<li>Create a new R Markdown document
<ul>
<li>Give it a proper title and select the <strong>PDF</strong> format</li>
</ul></li>
<li>Give the document some structure; e.g. create a segment (using single hash <code>#</code>) called <em>Exploratory Data Analysis</em>.</li>
<li>Whenever you add code to your document make sure that it is both readable (keep the maximum line length &lt; 100 if possible) and there is sufficient documentation either by text <strong>around</strong> the code ‘chunks’ (preferred) or by using comments <strong>within</strong> the code chunk.</li>
<li>Read in the data file(s)
<ul>
<li>Preferably use the <code>read.table</code> function and carefully set its arguments. Open the file in a text editor first to check its contents; does it have a header? can we set the <code>row.names</code>? Are all columns needed? etc.</li>
<li><strong>Note</strong>: if the data set consists of separate files (i.e. one per sample) or for general tips on reading in data, see the <a href="#a1-batch_data_loading">Appendix A: <em>Batch Loading Expression Data</em></a> chapter.</li>
<li>For the remainder of the document, try to show either the contents, structure or - in this case - dimensions of relevant R objects
<ul>
<li>Show the first five lines of the loaded data set. Including tables in a markdown document can be done using the <code>pander</code> function from the <code>pander</code><span class="citation">(<a href="#ref-R-pander">Daróczi and Tsegelskyi 2017</a>)</span> R-library.</li>
<li>Give the dimensions (with <code>dim()</code> and the structure (with <code>str()</code>) of the loaded data set.</li>
<li>Check the output of the <code>str</code> function to see if all columns are of the expected R data type (e.g. <code>values</code>, <code>factors</code>, <code>character</code>, etc.)</li>
</ul></li>
</ul></li>
<li>Examine the samples included in the experiment and create as many R character objects as needed to store the classification.
<ul>
<li><strong>Note</strong>: this is an important item and is often overlooked. See the <em>last 4 lines</em> in the code chunk in the section <a href="EDA.html#ch3_example_data">Example Data</a> below.</li>
<li>For instance, if you have eight samples divided into case/ control columns you create a variable called <code>case</code> in which you store the column <strong>indices</strong> (<strong>only</strong> numbers!) of the respective columns in the data set and a variable called <code>control</code> with the remaining four data column <strong>indices</strong>. These are for later use.</li>
<li>These variables allows us to repeatedly access the same data during the rest of this course, i.e. the code <code>boxplot(counts[case])</code> immediately shows that we are plotting the <code>case</code> samples from the <code>counts</code> data which is more clear than reading <code>boxplot(counts[c(5:8)])</code> as that gives no reference to what these indices mean and can lead to typing mistakes.</li>
</ul></li>
</ul>
<div class="rmdtip">
<p>
For some data sets the order in which the samples are listed in your
loaded data set is different from the order that is shown on the GEO
website. Most often, the names are different too or they are lacking any
description and all you have are non descriptive IDs. When creating
these variables such as <code>control</code> that need to point to all
control samples, you need to make sure that you have the right columns
from your data frame. Go to Appendix <a href="a2-annotation.html#download-geo">A2;
annotation</a> if the order is unclear or you just have a large number
of samples as there might be supporting data available that can help
make sense of your sample layout.
</p>
</div>
<p>If you want to include external images to your log and to better control properties such as <em>height</em> and <em>width</em> for individual images you can use the following code. Note: the code below is an <em>example</em> and you need to replace the <code>img_to_include.png</code> file path to an actual image.):</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="EDA.html#cb16-1" tabindex="-1"></a><span class="co"># Add the following to the code chunk header to control figure height, width and add a caption:</span></span>
<span id="cb16-2"><a href="EDA.html#cb16-2" tabindex="-1"></a><span class="co">#    {r, fig.height=5, fig.width=8, echo=FALSE, fig.cap=&quot;Image description&quot;}</span></span>
<span id="cb16-3"><a href="EDA.html#cb16-3" tabindex="-1"></a><span class="co"># The `dpi` argument is to remove any scaling</span></span>
<span id="cb16-4"><a href="EDA.html#cb16-4" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">&quot;figures/img_to_include.png&quot;</span>, <span class="at">dpi =</span> <span class="cn">NA</span>)</span></code></pre></div>
<p>See the <a href="https://yihui.org/knitr/options/">Knitr chunk options</a> page for a full listing of all chunk options.</p>
</div>
<div id="ch3_example_data" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Example Data</h2>
<p>This section lists all (publically available) data set(s) used in this chapter. Each chapter contains this section <em>if</em> new data sets are used there. Note that for <em>all</em> examples, your data <strong>will be different</strong> from the examples and one of the challenges during this course will be translating the examples to your own data. Keep in mind that simple copy-pasting of most code will fail for that reason. Most examples therefore will <em>print</em> the input data for comparison to your own data.</p>
<p>From the section <a href="EDA.html#normalization">Normalization</a> onwards, the experiment with identifier <a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE101942">GSE101942</a> is used for visualizing the normalized raw count values (the earlier sections explore the unnormalized data). This experiment is titled <em>“Transcriptome analysis of genetically matched human induced pluripotent stem cells disomic or trisomic for chromosome 21”</em> and the experimental setup is described as follows:</p>
<blockquote>
<p>“12 total polyA selected samples. 6 IPSC samples with 3 biological repeats for trisomic samples and 3 biological repeats for disomic samples. 6 IPSC derived neuronal samples with 3 biological repeats for trisomic samples and 3 biological repeats for disomic samples.”</p>
</blockquote>
<p>The following code shows how to load the two available files containing the raw-count data (one file per 6 samples), stored locally in the <code>data/gse101942/</code> folder. Some simple ‘cleanup’ steps are performed which aren’t required but helpful for demonstration purposes (i.e., renaming samples to identify groups).</p>
<ul>
<li><strong><code>GSE101942_IPSC_rawCounts.txt</code></strong>: raw count data for the induced pluripotent stem cells (iPSCs), both <em>trisomic</em> and <em>disomic</em></li>
<li><strong><code>GSE101942_Neuron_rawCounts.txt</code></strong>: raw count data for the IPSC-derived Neurons, both <em>trisomic</em> and <em>disomic</em>. These cells were treated to remove chromosome 21 from the iPSCs, as described by the treatment protocol as: “Targeted removal of CHR 21 in IPSC using TKNEO transgene”.</li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="EDA.html#cb17-1" tabindex="-1"></a><span class="co"># Load the two sets of 6 samples</span></span>
<span id="cb17-2"><a href="EDA.html#cb17-2" tabindex="-1"></a>ipsc.data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&#39;./data/gse101942/GSE101942_IPSC_rawCounts.txt&#39;</span>,</span>
<span id="cb17-3"><a href="EDA.html#cb17-3" tabindex="-1"></a>                        <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-4"><a href="EDA.html#cb17-4" tabindex="-1"></a>neuron.data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&#39;./data/gse101942/GSE101942_Neuron_rawCounts.txt&#39;</span>,</span>
<span id="cb17-5"><a href="EDA.html#cb17-5" tabindex="-1"></a>                          <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb17-6"><a href="EDA.html#cb17-6" tabindex="-1"></a><span class="co"># Merge by rowname (by = 0, see the help of &#39;merge&#39;)</span></span>
<span id="cb17-7"><a href="EDA.html#cb17-7" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">merge</span>(ipsc.data, neuron.data, <span class="at">by =</span> <span class="dv">0</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>, <span class="at">all.y =</span> <span class="cn">TRUE</span>,</span>
<span id="cb17-8"><a href="EDA.html#cb17-8" tabindex="-1"></a>                <span class="at">sort =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-9"><a href="EDA.html#cb17-9" tabindex="-1"></a><span class="co"># Change all NA&#39;s introduced by the merge to zeros</span></span>
<span id="cb17-10"><a href="EDA.html#cb17-10" tabindex="-1"></a>counts[<span class="fu">is.na</span>(counts)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb17-11"><a href="EDA.html#cb17-11" tabindex="-1"></a><span class="co"># Show column names coming from the input files</span></span>
<span id="cb17-12"><a href="EDA.html#cb17-12" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">names</span>(counts))</span></code></pre></div>
<pre><code>##  [1] &quot;Row.names&quot; &quot;c244A&quot;     &quot;c244B&quot;     &quot;c243&quot;      &quot;c2A&quot;       &quot;c2B&quot;      
##  [7] &quot;c2C&quot;       &quot;C3_1&quot;      &quot;C3_2&quot;      &quot;C3_4&quot;      &quot;C2_2_1&quot;    &quot;C2_2_2&quot;   
## [13] &quot;C2_2_3&quot;</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="EDA.html#cb19-1" tabindex="-1"></a><span class="co"># Set the row names to the gene IDs stored in the &#39;Row.names&#39; column</span></span>
<span id="cb19-2"><a href="EDA.html#cb19-2" tabindex="-1"></a><span class="fu">row.names</span>(counts) <span class="ot">&lt;-</span> counts<span class="sc">$</span>Row.names</span>
<span id="cb19-3"><a href="EDA.html#cb19-3" tabindex="-1"></a><span class="co"># Remove the gene ID column</span></span>
<span id="cb19-4"><a href="EDA.html#cb19-4" tabindex="-1"></a>counts <span class="ot">&lt;-</span> counts[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb19-5"><a href="EDA.html#cb19-5" tabindex="-1"></a><span class="co"># Rename samples to include their group name</span></span>
<span id="cb19-6"><a href="EDA.html#cb19-6" tabindex="-1"></a><span class="fu">names</span>(counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">paste0</span>(<span class="st">&#39;di_IPSC_r&#39;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),  <span class="co"># Disomic IPSC, replicates 1-3</span></span>
<span id="cb19-7"><a href="EDA.html#cb19-7" tabindex="-1"></a>                   <span class="fu">paste0</span>(<span class="st">&#39;tri_IPSC_r&#39;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>), <span class="co"># Trisomic IPSC, replicates 1-3</span></span>
<span id="cb19-8"><a href="EDA.html#cb19-8" tabindex="-1"></a>                   <span class="fu">paste0</span>(<span class="st">&#39;di_NEUR_r&#39;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),  <span class="co"># Disomic Neuron, replicates 1-3</span></span>
<span id="cb19-9"><a href="EDA.html#cb19-9" tabindex="-1"></a>                   <span class="fu">paste0</span>(<span class="st">&#39;tri_NEUR_r&#39;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)) <span class="co"># Trisomic Neuron, replicates 1-3</span></span>
<span id="cb19-10"><a href="EDA.html#cb19-10" tabindex="-1"></a><span class="co"># Show results of renaming the samples</span></span>
<span id="cb19-11"><a href="EDA.html#cb19-11" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">names</span>(counts))</span></code></pre></div>
<pre><code>##  [1] &quot;di_IPSC_r1&quot;  &quot;di_IPSC_r2&quot;  &quot;di_IPSC_r3&quot;  &quot;tri_IPSC_r1&quot; &quot;tri_IPSC_r2&quot;
##  [6] &quot;tri_IPSC_r3&quot; &quot;di_NEUR_r1&quot;  &quot;di_NEUR_r2&quot;  &quot;di_NEUR_r3&quot;  &quot;tri_NEUR_r1&quot;
## [11] &quot;tri_NEUR_r2&quot; &quot;tri_NEUR_r3&quot;</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="EDA.html#cb21-1" tabindex="-1"></a><span class="co"># Assign column -indices- to variables for later use (i.e. counts[di_NEUR] selects the relevant columns)</span></span>
<span id="cb21-2"><a href="EDA.html#cb21-2" tabindex="-1"></a>di_IPSC <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span></span>
<span id="cb21-3"><a href="EDA.html#cb21-3" tabindex="-1"></a>tri_IPSC <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">:</span><span class="dv">6</span></span>
<span id="cb21-4"><a href="EDA.html#cb21-4" tabindex="-1"></a>di_NEUR <span class="ot">&lt;-</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">9</span></span>
<span id="cb21-5"><a href="EDA.html#cb21-5" tabindex="-1"></a>tri_NEUR <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">:</span><span class="dv">12</span></span></code></pre></div>
<p>See <em>Table 1</em> in the <a href="EDA.html#normalization">Normalization</a> section for the resulting contents in the <code>counts</code> dataframe.</p>
</div>
<div id="EDA_part1" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Visualizing using <code>boxplot</code> and <code>density plot</code></h2>
<p>This segment describes some of the basic steps and a visualization that can be performed during Exploratory Data Analysis. We start by inspecting the unnormalized count data. For the next steps normalization is applied as shown in the <a href="EDA.html#normalization">Normalization</a> section below. As mentioned above, the focus of EDA is to get an overview/ perform a bit of Quality Control of the data set and while this often requires visualizing the data, these figures do not need to be very pretty. Simple figures are perfectly fine in this stage. Try to create these figures for your own data (and keep them in your log) <strong>and</strong> add a small description for each figure pointing out anything that is different from what you expect.</p>
<p>Also note that these steps are just a selection. Furthermore, make sure that for every visualization you make, add proper axis-labels containing the measurement units (important!). As you might be able to see, all values are <em>log-transformed</em> using the <code>log2</code> function because very often the numerical values have a very high range which will ‘hide’ the details on the plots. See the section about the <a href="chapter-4.html#deg-fc">Fold Change value</a> in chapter 4 for further details. It is fine to use non-log-transformed (simply the raw-)data, otherwise use for instance <code>boxplot(log2(dataset))</code> for plotting.</p>
<div class="rmdtip">
<p>
Instead of using the basic R-plotting library
(i.e. <code>plot</code>, <code>boxplot</code>, <code>hist</code>, etc.)
you can also opt for using the (challenging) <a
href="http://ggplot2.tidyverse.org/index.html"><code>ggplot2</code></a>
library that is also used for the boxplot in the following section.
While constructing a <code>ggplot2</code> plot feels like learning yet
another language, there are many resources available online that you can
follow.
</p>
</div>
<div id="eda_statistics" class="section level3" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Statistics</h3>
<p>Even the most basic statistics can give some insight into the data such as performing a 6-number-statistic on the data <strong>columns</strong> using the <code>summary()</code> function. Note: you can also use the <code>pander</code> function to <em>pretty-print</em> a summary in the knitted output. What do you notice if you look at the numbers produced by executing this function on the complete data set?</p>
</div>
<div id="eda_boxplots" class="section level3" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Boxplots</h3>
<p>A visual representation of these values can be shown using a boxplot. Boxplots are very easy to create from an R data frame object by just passing in the data columns. The following boxplot shows the data for an experiment with a separate boxplot for each sample. This allows a quick overview for spotting irregularities (i.e. checking if the replicates within a sample-group show similar expression profiles). Of course, if we consider the amount of data in this single plot, it can only hint at any problems, we need to look in much more detail when doing any form of quality control. Creating a boxplot from a <code>dataframe</code> is easy, but as we saw with using the <code>summary</code> function; the data has a large range with the maximum and average values being very far apart. This will create a lot of <em>outliers</em> in the plot which will be interesting later on, but for the boxplot we can either:</p>
<ul>
<li>hide them completely using the <code>outline = FALSE</code> argument to <code>boxplot()</code> (do say so in the figure description!), or</li>
<li>perform a <code>log2()</code> transformation as you can see below.</li>
</ul>
<div class="rmdtip">
<p>
When creating plots of expression data without performing
log-transformations we see that (for instance with the boxplot) the
range of data is very large (from 0 up to 1.000.000) with a <em>lot</em>
of outliers in the upper range. This makes for not very informative
figures, so placing a simple <code>log2()</code> function call around
the data <em>almost</em> resolves this issue.
</p>
<p>
However, this might introduce another problem (taking the boxplot as
an example) because this log-transformation results in data that
contains <em>negative infinity</em> (<code>-Inf</code>) values. These
are caused by all the 0-values in the data since
<code>log2(0) == -Inf</code>. To circumvent this issue, we can add a
<em>pseudo count</em> to the data by simply adding the value
<code>1</code> to all count values since the <code>log2(1) == 0</code>;
<code>log2(counts + 1)</code>.
</p>
<p>
There are more situations other than the boxplot where adding a
pseudo count value to the complete dataset can be useful. Always add a
pseudocount <em>in-place</em>, meaning within the plotting code instead
of overwriting your original data set with a pseudo count added as not
all steps require this. In some cases (see the <a
href="#eda_density_plot">density plot</a> below) it can be useful to
clearly separate the 0-values from the rest in which case a
<code>0 &lt; pseudo count &lt; 1</code> value, such as <code>0.1</code>
can be used as this generates a negative value (<code>-3.3</code>) that
is far away from the rest of the data. All other count values are always
&gt;0 which result in a positive log2 value.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:edaBoxplot"></span>
<img src="chapters/images/RNAboxplot_ggplot2.png" alt="Boxplot comparing basic statistics for all genes across multiple samples"  />
<p class="caption">
Figure 3.1: Boxplot comparing basic statistics for all genes across multiple samples
</p>
</div>
</div>
<div id="eda_density_plot" class="section level3" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Density Plots</h3>
<p>Another form of visualizing the same data is using a density plot. This method shows a distribution of the (log2-transformed) count data for all samples and allows for easy spotting of problems. While this plot is more commonly used in analysing microarrays, it is still useful for comparing the complete dataset. The code and figure below show an example distribution for 12 samples. A few things to note about this figure is that there is a huge peak at exactly <code>-3.321928</code> which can be ignored because this is value is calculated from <code>log2(0.1)</code> explained in the box above. This peak consists of all 0-values (inactive genes) which isn’t very important to us now. Therefore, we added a vertical line to indicate the left-part is of little interest. Note: a lot of the code below is extra, for a simple inspection using <em>only</em> the line <code>plotDensity(log2(counts + 0.1))</code> is enough, the rest is extra example code.</p>
<p>To assess the quality of the data we look at the peaks in the plot. The heigth of the peak doesn’t matter much, shifted peaks do however as those indicate either a lower or higher amount of reads sequenced for that sample. This can be confirmed with the first plot demonstrated below in the next section where the <em>library-sizes</em> are visualized.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="EDA.html#cb22-1" tabindex="-1"></a><span class="do">## The affy library has a density plotting function</span></span>
<span id="cb22-2"><a href="EDA.html#cb22-2" tabindex="-1"></a><span class="fu">library</span>(affy)</span>
<span id="cb22-3"><a href="EDA.html#cb22-3" tabindex="-1"></a></span>
<span id="cb22-4"><a href="EDA.html#cb22-4" tabindex="-1"></a><span class="do">## Create a list of 4 colors to use which are the same used throughout this chapter </span></span>
<span id="cb22-5"><a href="EDA.html#cb22-5" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb22-6"><a href="EDA.html#cb22-6" tabindex="-1"></a>myColors <span class="ot">&lt;-</span> <span class="fu">hue_pal</span>()(<span class="dv">4</span>)</span>
<span id="cb22-7"><a href="EDA.html#cb22-7" tabindex="-1"></a></span>
<span id="cb22-8"><a href="EDA.html#cb22-8" tabindex="-1"></a><span class="do">## Plot the log2-transformed data with a 0.1 pseudocount</span></span>
<span id="cb22-9"><a href="EDA.html#cb22-9" tabindex="-1"></a><span class="fu">plotDensity</span>(<span class="fu">log2</span>(counts <span class="sc">+</span> <span class="fl">0.1</span>), <span class="at">col=</span><span class="fu">rep</span>(myColors, <span class="at">each=</span><span class="dv">3</span>),</span>
<span id="cb22-10"><a href="EDA.html#cb22-10" tabindex="-1"></a>            <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(counts)), <span class="at">xlab=</span><span class="st">&#39;Log2(count)&#39;</span>,</span>
<span id="cb22-11"><a href="EDA.html#cb22-11" tabindex="-1"></a>            <span class="at">main=</span><span class="st">&#39;Expression Distribution&#39;</span>)</span>
<span id="cb22-12"><a href="EDA.html#cb22-12" tabindex="-1"></a></span>
<span id="cb22-13"><a href="EDA.html#cb22-13" tabindex="-1"></a><span class="do">## Add a legend and vertical line</span></span>
<span id="cb22-14"><a href="EDA.html#cb22-14" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&#39;topright&#39;</span>, <span class="fu">names</span>(counts), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(counts)),</span>
<span id="cb22-15"><a href="EDA.html#cb22-15" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">rep</span>(myColors, <span class="at">each=</span><span class="dv">3</span>))</span>
<span id="cb22-16"><a href="EDA.html#cb22-16" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="sc">-</span><span class="fl">1.5</span>, <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&#39;red&#39;</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:densityPlot"></span>
<img src="chapters/images/RNAdensityplot.png" alt="Density plot comparing count distribution for 12 samples"  />
<p class="caption">
Figure 3.2: Density plot comparing count distribution for 12 samples
</p>
</div>
</div>
</div>
<div id="EDA_part2" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Visualizing using <code>heatmap</code> and <code>MDS</code></h2>
<p>This section adds a few Exploratory Data Analysis techniques where we will measure and look at <em>distances</em> between samples based on <em>normalized</em> data. Measuring distances between two data objects (samples in our case) is a common task in cluster analysis to compare similarity (low distance indicates similar data). In this case we will calculate the distances between our samples and visualize them in a <code>heatmap</code> and using a <code>multidimensional scaling</code> (MDS) technique.</p>
<p>In the previous section we used the raw count data. You might have one or more samples that have different values (i.e. shifted) compared to other samples. While we need the raw count data to use R packages such as <code>edgeR</code> <span class="citation">(<a href="#ref-R-edgeR">Chen et al. 2018</a>)</span> and <code>DESeq2</code> <span class="citation">(<a href="#ref-R-DESeq2">Love, Anders, and Huber 2017</a>)</span>, calculating sample distances (used in the visualizations in this section) should be done on some form of normalized data. This data can either be RPKM/FPKM/TPM/CPM or vst-transformed (raw-)read counts. A proper method of transforming raw read count data is using the <code>vst</code> method from the <code>DESeq2</code> R Bioconductor library which is shown below. This ‘<em>variance stabilizing transformation</em>’ normalized data will only be used in this chapter, in chapter 4 we will again normalize using a different technique.</p>
<p>The following code examples shows how to use this library to normalize the count data from the <strong>GSE101942</strong> experiment to vst-normalized data before we calculate a distance metric.</p>
<table style="width:94%;">
<colgroup>
<col width="20%" />
<col width="18%" />
<col width="18%" />
<col width="18%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">di_IPSC_r1</th>
<th align="center">di_IPSC_r2</th>
<th align="center">di_IPSC_r3</th>
<th align="center">tri_IPSC_r1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>5S_rRNA</strong></td>
<td align="center">4</td>
<td align="center">6</td>
<td align="center">4</td>
<td align="center">17</td>
</tr>
<tr class="even">
<td align="center"><strong>7SK</strong></td>
<td align="center">79</td>
<td align="center">57</td>
<td align="center">28</td>
<td align="center">96</td>
</tr>
<tr class="odd">
<td align="center"><strong>A1BG</strong></td>
<td align="center">16</td>
<td align="center">8</td>
<td align="center">12</td>
<td align="center">15</td>
</tr>
<tr class="even">
<td align="center"><strong>A1BG-AS1</strong></td>
<td align="center">267</td>
<td align="center">253</td>
<td align="center">166</td>
<td align="center">316</td>
</tr>
<tr class="odd">
<td align="center"><strong>A1CF</strong></td>
<td align="center">2</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">4</td>
</tr>
<tr class="even">
<td align="center"><strong>A2M</strong></td>
<td align="center">10</td>
<td align="center">8</td>
<td align="center">7</td>
<td align="center">48</td>
</tr>
</tbody>
</table>
<p>Table 1; Raw count data for <code>GSE101942</code> (continued below)</p>
<table style="width:96%;">
<colgroup>
<col width="20%" />
<col width="19%" />
<col width="19%" />
<col width="18%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">tri_IPSC_r2</th>
<th align="center">tri_IPSC_r3</th>
<th align="center">di_NEUR_r1</th>
<th align="center">di_NEUR_r2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>5S_rRNA</strong></td>
<td align="center">13</td>
<td align="center">12</td>
<td align="center">22</td>
<td align="center">16</td>
</tr>
<tr class="even">
<td align="center"><strong>7SK</strong></td>
<td align="center">134</td>
<td align="center">38</td>
<td align="center">26</td>
<td align="center">26</td>
</tr>
<tr class="odd">
<td align="center"><strong>A1BG</strong></td>
<td align="center">39</td>
<td align="center">22</td>
<td align="center">583</td>
<td align="center">938</td>
</tr>
<tr class="even">
<td align="center"><strong>A1BG-AS1</strong></td>
<td align="center">339</td>
<td align="center">211</td>
<td align="center">680</td>
<td align="center">659</td>
</tr>
<tr class="odd">
<td align="center"><strong>A1CF</strong></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center"><strong>A2M</strong></td>
<td align="center">8</td>
<td align="center">4</td>
<td align="center">59</td>
<td align="center">910</td>
</tr>
</tbody>
</table>
<p>Table continues below</p>
<table style="width:97%;">
<colgroup>
<col width="20%" />
<col width="18%" />
<col width="19%" />
<col width="19%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">di_NEUR_r3</th>
<th align="center">tri_NEUR_r1</th>
<th align="center">tri_NEUR_r2</th>
<th align="center">tri_NEUR_r3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>5S_rRNA</strong></td>
<td align="center">0</td>
<td align="center">26</td>
<td align="center">9</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>7SK</strong></td>
<td align="center">71</td>
<td align="center">32</td>
<td align="center">14</td>
<td align="center">40</td>
</tr>
<tr class="odd">
<td align="center"><strong>A1BG</strong></td>
<td align="center">809</td>
<td align="center">1030</td>
<td align="center">461</td>
<td align="center">987</td>
</tr>
<tr class="even">
<td align="center"><strong>A1BG-AS1</strong></td>
<td align="center">1165</td>
<td align="center">636</td>
<td align="center">449</td>
<td align="center">1257</td>
</tr>
<tr class="odd">
<td align="center"><strong>A1CF</strong></td>
<td align="center">2</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>A2M</strong></td>
<td align="center">520</td>
<td align="center">592</td>
<td align="center">155</td>
<td align="center">74</td>
</tr>
</tbody>
</table>
<p>If you look at <code>Table 1</code> you immediately see a huge difference between the groups for each of the genes. The gene (<code>A1BG</code>) shows <strong>&gt;100</strong> more expression in the <code>tri_NEUR</code> group compared to the <code>di_IPSC</code> group, but within most groups there is a very high variation too indicating that it might not be the actual expression that is different. One very simple and quick method of inspection is looking at the total number of mapped reads per sample (the sum of each sample/ column), as the <em>sequencing-depth</em> might vary across samples.</p>
<p><strong>Hint</strong>:</p>
<p>Simple version of this plot can be achieved with <code>barplot(colSums(counts) / 1e6)</code></p>
<table>
<colgroup>
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="17%" />
<col width="17%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">di_IPSC_r1</th>
<th align="center">di_IPSC_r2</th>
<th align="center">di_IPSC_r3</th>
<th align="center">tri_IPSC_r1</th>
<th align="center">tri_IPSC_r2</th>
<th align="center">tri_IPSC_r3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">108</td>
<td align="center">108</td>
<td align="center">81</td>
<td align="center">112</td>
<td align="center">134</td>
<td align="center">83</td>
</tr>
</tbody>
</table>
<p>Table 2; Mapped reads per sample (millions) (continued below)</p>
<table>
<colgroup>
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="17%" />
<col width="17%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">di_NEUR_r1</th>
<th align="center">di_NEUR_r2</th>
<th align="center">di_NEUR_r3</th>
<th align="center">tri_NEUR_r1</th>
<th align="center">tri_NEUR_r2</th>
<th align="center">tri_NEUR_r3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">70</td>
<td align="center">94</td>
<td align="center">114</td>
<td align="center">108</td>
<td align="center">48</td>
<td align="center">140</td>
</tr>
</tbody>
</table>
<div class="figure"><span style="display:block;" id="fig:librarySizes"></span>
<img src="gene_expression_files/figure-html/librarySizes-1.png" alt="Library sizes for all samples from GSE101942" width="672" />
<p class="caption">
Figure 3.3: Library sizes for all samples from GSE101942
</p>
</div>
<p>The numbers shown in <code>Table 2</code> and the barplot above immediately clarify that it is not just the experimental condition that might have caused this large difference between sample counts but the sequencing depth shows a substantial difference too. Both the minimum and maximum sequencing depth are within the trisomic neuron group (purple in the barplot). The average expression of the <code>A1BG</code> gene within this group is 820, but with a minimum of 461 and a maximum of 1010 there is a lot of variation. This is one more reason telling us that we will have to <strong>normalize</strong> the data. The following code chunks show how to do this with <code>DESeq2</code>’s <code>vst</code> method (<em>variance stabilizing transformation</em>). Check the <code>Packages</code> tab in Rstudio to see if you have the <code>DESeq2</code> package installed and load it with the <code>library</code> command.</p>
<div id="normalization" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Normalization</h3>
<p>To use the <code>vst</code> function from the <code>DESeq2</code> library we must construct a <code>DESeqDataSet</code>-object consisting of the count data combined with sample annotation. Since we only want to use it (for now) for performing a vst-transformation we use the most basic form with a very simple <code>design</code> and the sample names as annotation (the <code>colData</code> argument):</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="EDA.html#cb23-1" tabindex="-1"></a><span class="co"># Load the library</span></span>
<span id="cb23-2"><a href="EDA.html#cb23-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&#39;DESeq2&#39;</span>)</span>
<span id="cb23-3"><a href="EDA.html#cb23-3" tabindex="-1"></a></span>
<span id="cb23-4"><a href="EDA.html#cb23-4" tabindex="-1"></a><span class="co"># DESeq2 will construct a SummarizedExperiment object and combine this </span></span>
<span id="cb23-5"><a href="EDA.html#cb23-5" tabindex="-1"></a><span class="co"># into a &#39;DESeqDataSet&#39; object. The &#39;design&#39; argument usually indicates the </span></span>
<span id="cb23-6"><a href="EDA.html#cb23-6" tabindex="-1"></a><span class="co"># experimental design using the condition(s) names as a &#39;factor&#39;, for now we use just &#39;~ 1&#39;</span></span>
<span id="cb23-7"><a href="EDA.html#cb23-7" tabindex="-1"></a>(ddsMat <span class="ot">&lt;-</span> <span class="fu">DESeqDataSetFromMatrix</span>(<span class="at">countData =</span> counts,</span>
<span id="cb23-8"><a href="EDA.html#cb23-8" tabindex="-1"></a>                                  <span class="at">colData =</span> <span class="fu">data.frame</span>(<span class="at">samples =</span> <span class="fu">names</span>(counts)),</span>
<span id="cb23-9"><a href="EDA.html#cb23-9" tabindex="-1"></a>                                  <span class="at">design =</span> <span class="sc">~</span> <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## class: DESeqDataSet 
## dim: 56640 12 
## metadata(1): version
## assays(1): counts
## rownames(56640): 5S_rRNA 7SK ... C1orf220 C2orf15
## rowData names(0):
## colnames(12): di_IPSC_r1 di_IPSC_r2 ... tri_NEUR_r2 tri_NEUR_r3
## colData names(1): samples</code></pre>
<p>We now have a proper <code>DESeqDataSet</code> object as you can see above, containing 56640 rows and 12 columns (genes and samples) with the gene symbols as row names. Usually this object would hold more data, but as this is only a requirement to perform the <code>vst</code> transformation it is good enough for now. Next step is performing this transformation (this can take a while depending on the size of the experiment and results in a <code>Large DESeqTransform</code> object) and retrieving the actual data from this with the <code>assay</code> function as this object too contains a lot of meta-data. The table below shows the updated values which are now comparable across genes whereas the raw count data was harder to compare.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="EDA.html#cb25-1" tabindex="-1"></a><span class="co"># Perform normalization</span></span>
<span id="cb25-2"><a href="EDA.html#cb25-2" tabindex="-1"></a>rld.dds <span class="ot">&lt;-</span> <span class="fu">vst</span>(ddsMat)</span>
<span id="cb25-3"><a href="EDA.html#cb25-3" tabindex="-1"></a><span class="co"># &#39;Extract&#39; normalized values</span></span>
<span id="cb25-4"><a href="EDA.html#cb25-4" tabindex="-1"></a>rld <span class="ot">&lt;-</span> <span class="fu">assay</span>(rld.dds)</span></code></pre></div>
<table style="width:75%;">
<colgroup>
<col width="20%" />
<col width="18%" />
<col width="18%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">di_IPSC_r1</th>
<th align="center">di_IPSC_r2</th>
<th align="center">di_IPSC_r3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>5S_rRNA</strong></td>
<td align="center">3.704</td>
<td align="center">4.015</td>
<td align="center">3.876</td>
</tr>
<tr class="even">
<td align="center"><strong>7SK</strong></td>
<td align="center">6.726</td>
<td align="center">6.36</td>
<td align="center">5.747</td>
</tr>
<tr class="odd">
<td align="center"><strong>A1BG</strong></td>
<td align="center">4.842</td>
<td align="center">4.243</td>
<td align="center">4.813</td>
</tr>
<tr class="even">
<td align="center"><strong>A1BG-AS1</strong></td>
<td align="center">8.385</td>
<td align="center">8.37</td>
<td align="center">8.083</td>
</tr>
<tr class="odd">
<td align="center"><strong>A1CF</strong></td>
<td align="center">3.322</td>
<td align="center">2.343</td>
<td align="center">2.343</td>
</tr>
<tr class="even">
<td align="center"><strong>A2M</strong></td>
<td align="center">4.397</td>
<td align="center">4.243</td>
<td align="center">4.312</td>
</tr>
</tbody>
</table>
<p>Table 2; VST transformed disomic IPSC count data</p>
<p>Note that when again looking at the <code>A1BG</code> gene (the one displayed in figure 3.8), the normalized expression values show much less variation across the samples (not shown, but also within each sample group). Therefore, we assume that the large difference in expression we observed earlier might be non-existent (there might still be a significant difference though!).</p>
</div>
<div id="eda_distance" class="section level3" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Distance Calculation</h3>
<p>We now have normalized data that we can use for distance calculation. This is a standard procedure for many data analysis tasks as it calculates a distance metric for each combination of samples that we will use to check for variation <em>within</em> the sample groups. We first need to <a href="https://en.wikipedia.org/wiki/Transpose"><em>transpose</em></a> the matrix (<code>rld</code>) of normalized values using the <code>t</code>-function, because the <code>dist</code> function expects the different samples as rows and the genes as columns. Note that the output matrix is symmetric. Table 3 below shows the calculated distances within the disomic IPSC group where the distance between samples varies from 100 to 140. The maximum distance between any samples is 380 as will be demonstrated with the visualizations in the next sections.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="EDA.html#cb26-1" tabindex="-1"></a><span class="co"># Calculate basic distance metric (using euclidean distance, see &#39;?dist&#39;)</span></span>
<span id="cb26-2"><a href="EDA.html#cb26-2" tabindex="-1"></a>sampledists <span class="ot">&lt;-</span> <span class="fu">dist</span>( <span class="fu">t</span>( rld ))</span></code></pre></div>
<table style="width:78%;">
<colgroup>
<col width="23%" />
<col width="18%" />
<col width="18%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">di_IPSC_r1</th>
<th align="center">di_IPSC_r2</th>
<th align="center">di_IPSC_r3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>di_IPSC_r1</strong></td>
<td align="center">0</td>
<td align="center">107.6</td>
<td align="center">147.7</td>
</tr>
<tr class="even">
<td align="center"><strong>di_IPSC_r2</strong></td>
<td align="center">107.6</td>
<td align="center">0</td>
<td align="center">139.7</td>
</tr>
<tr class="odd">
<td align="center"><strong>di_IPSC_r3</strong></td>
<td align="center">147.7</td>
<td align="center">139.7</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<p>Table 3; Sample distances for the disomic IPSCs (Euclidean method)</p>
</div>
<div id="eda_heatmap" class="section level3" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> Sample Distances using a Heatmap</h3>
<p>If you have both (raw-)count data <em>and</em> an other normalized format (TPM, RPKM, etc.), you can <em>optionally</em> follow the above procedure for your count data and create a heatmap for <strong>both</strong> formats to see if this makes any difference. The reason for this is that while the RNA-Seq method exists for over 10 years, there are still ongoing discussions on the subject of data processing, especially regarding subjects like which normalization technque to use for which data analysis.</p>
<p>The following code block creates a heatmap using the <code>pheatmap</code> library which offers on of the many available heatmap functions. Using the <code>annotation</code> data frame (you can inspect the contents of it yourself) we identify the samples based on both the cell type and the ploidy. The clustering shown in the heatmap clearly separates the data based on the cell type and the differences between the ploidy seems to be minimal. Looking further still, the differences <em>within</em> a single group are minimal too meaning that we are not - yet - inclined to remove any outlier-samples. Since we have only have 3 samples per category, we would also lose statistical power if we eventually were to remove one or more samples (also, always check the article to see if they did remove any samples prior to the data analysis).</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="EDA.html#cb27-1" tabindex="-1"></a><span class="co"># We use the &#39;pheatmap&#39; library (install with install.packages(&#39;pheatmap&#39;))</span></span>
<span id="cb27-2"><a href="EDA.html#cb27-2" tabindex="-1"></a><span class="fu">library</span>(pheatmap)</span>
<span id="cb27-3"><a href="EDA.html#cb27-3" tabindex="-1"></a></span>
<span id="cb27-4"><a href="EDA.html#cb27-4" tabindex="-1"></a><span class="co"># Convert the &#39;dist&#39; object into a matrix for creating a heatmap</span></span>
<span id="cb27-5"><a href="EDA.html#cb27-5" tabindex="-1"></a>sampleDistMatrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(sampledists)</span>
<span id="cb27-6"><a href="EDA.html#cb27-6" tabindex="-1"></a></span>
<span id="cb27-7"><a href="EDA.html#cb27-7" tabindex="-1"></a><span class="co"># The annotation is an extra layer that will be plotted above the heatmap columns</span></span>
<span id="cb27-8"><a href="EDA.html#cb27-8" tabindex="-1"></a><span class="co"># indicating the cell type</span></span>
<span id="cb27-9"><a href="EDA.html#cb27-9" tabindex="-1"></a>annotation <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Cell =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">each =</span> <span class="dv">6</span>), </span>
<span id="cb27-10"><a href="EDA.html#cb27-10" tabindex="-1"></a>                                          <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;IPSC&quot;</span>, <span class="st">&quot;Neuron&quot;</span>)),</span>
<span id="cb27-11"><a href="EDA.html#cb27-11" tabindex="-1"></a>                         <span class="at">Ploidy =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">each =</span> <span class="dv">3</span>), <span class="dv">2</span>),</span>
<span id="cb27-12"><a href="EDA.html#cb27-12" tabindex="-1"></a>                                         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;disomic&quot;</span>, <span class="st">&quot;trisomic&quot;</span>)))</span>
<span id="cb27-13"><a href="EDA.html#cb27-13" tabindex="-1"></a>                         </span>
<span id="cb27-14"><a href="EDA.html#cb27-14" tabindex="-1"></a><span class="co"># Set the rownames of the annotation dataframe to the sample names (required)</span></span>
<span id="cb27-15"><a href="EDA.html#cb27-15" tabindex="-1"></a><span class="fu">rownames</span>(annotation) <span class="ot">&lt;-</span> <span class="fu">names</span>(counts)</span>
<span id="cb27-16"><a href="EDA.html#cb27-16" tabindex="-1"></a></span>
<span id="cb27-17"><a href="EDA.html#cb27-17" tabindex="-1"></a><span class="fu">pheatmap</span>(sampleDistMatrix, <span class="at">show_colnames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb27-18"><a href="EDA.html#cb27-18" tabindex="-1"></a>         <span class="at">annotation_col =</span> annotation,</span>
<span id="cb27-19"><a href="EDA.html#cb27-19" tabindex="-1"></a>         <span class="at">clustering_distance_rows =</span> sampledists,</span>
<span id="cb27-20"><a href="EDA.html#cb27-20" tabindex="-1"></a>         <span class="at">clustering_distance_cols =</span> sampledists,</span>
<span id="cb27-21"><a href="EDA.html#cb27-21" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">&quot;Euclidean Sample Distances&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:pheatmapDistances"></span>
<img src="gene_expression_files/figure-html/pheatmapDistances-1.png" alt="Heatmap showing the Euclidean distances between all samples" width="672" />
<p class="caption">
Figure 3.4: Heatmap showing the Euclidean distances between all samples
</p>
</div>
<p>The resulting heatmap shows an interesting comparison across all samples where the order of samples is purely determined using the distance and is often different from the order in the data set. Ideally, we want the sample groups to be clustered together as we see with this data. This particular heatmap clearly shows a large difference in overal expression between the induced pluripotent stem cells (iPSCs) and their differentiated cortical neurons while the difference - within cell type - between disomic and trisomic is much lower.</p>
</div>
<div id="eda_mds" class="section level3" number="3.4.4">
<h3><span class="header-section-number">3.4.4</span> Multi-Dimensional Scaling</h3>
<p>The following code example shows how to perform Multi-Dimensional Scaling (MDS) that displays similarly calculated distances in a 2D-plot. With an experiment like this with two groups of samples, we hope to see two clearly separated clusters formed, however as we’ve seen in the heatmap, sample <code>KO1B</code> showed a large deviation which we will also see (confirm) using MDS.</p>
<div class="rmdtip">
<p>
The figure below is plotted using <code>ggplot2</code>, a more
advanced method of plotting in R. While these plots are preferred over
base-R plotting, it is always sufficient to use just that as it can be
very challenging to alter the example code shown in this section. The
data object plotted is shown and in this case contains simple X- and
Y-coordinates.
</p>
</div>
<p>For MDS we use a slightly different distance metric (Poisson instead of the default <code>euclidean</code> used in the <code>dist</code> function). The following code shows how to calculate a more fitting distance for sequencing data called the <em>Poisson Distance</em> with a number of optimizations available in the <code>PoiClaClu</code> library. This library was specifically designed to handle read count data and is less influenced by read-count differences across samples. Note that again, the code below is only usable for <strong>count</strong> data as this function requires:</p>
<blockquote>
<p>An n-by-p data matrix with observations on the rows, and p features on the columns. The (i,j) element of x is the <strong>number of reads</strong> in observation i that mapped to feature (e.g. gene or exon) j.</p>
</blockquote>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="EDA.html#cb28-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&#39;PoiClaClu&#39;</span>)</span>
<span id="cb28-2"><a href="EDA.html#cb28-2" tabindex="-1"></a><span class="co"># Note: uses the raw-count data, PoissonDistance performs normalization</span></span>
<span id="cb28-3"><a href="EDA.html#cb28-3" tabindex="-1"></a><span class="co"># set by the &#39;type&#39; parameter (uses DESeq)</span></span>
<span id="cb28-4"><a href="EDA.html#cb28-4" tabindex="-1"></a>dds <span class="ot">&lt;-</span> <span class="fu">assay</span>(ddsMat)</span>
<span id="cb28-5"><a href="EDA.html#cb28-5" tabindex="-1"></a>poisd <span class="ot">&lt;-</span> <span class="fu">PoissonDistance</span>( <span class="fu">t</span>(dds), <span class="at">type =</span> <span class="st">&quot;deseq&quot;</span>)</span>
<span id="cb28-6"><a href="EDA.html#cb28-6" tabindex="-1"></a><span class="co"># Extract the matrix with distances</span></span>
<span id="cb28-7"><a href="EDA.html#cb28-7" tabindex="-1"></a>samplePoisDistMatrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(poisd<span class="sc">$</span>dd)</span>
<span id="cb28-8"><a href="EDA.html#cb28-8" tabindex="-1"></a><span class="co"># Calculate the MDS and get the X- and Y-coordinates</span></span>
<span id="cb28-9"><a href="EDA.html#cb28-9" tabindex="-1"></a>mdsPoisData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="fu">cmdscale</span>(samplePoisDistMatrix) )</span>
<span id="cb28-10"><a href="EDA.html#cb28-10" tabindex="-1"></a></span>
<span id="cb28-11"><a href="EDA.html#cb28-11" tabindex="-1"></a><span class="co"># And set some better readable names for the columns</span></span>
<span id="cb28-12"><a href="EDA.html#cb28-12" tabindex="-1"></a><span class="fu">names</span>(mdsPoisData) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;x_coord&#39;</span>, <span class="st">&#39;y_coord&#39;</span>)</span></code></pre></div>
<table style="width:28%;">
<colgroup>
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">x_coord</th>
<th align="center">y_coord</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">-22016</td>
<td align="center">-3828</td>
</tr>
<tr class="even">
<td align="center">-22069</td>
<td align="center">-8.734</td>
</tr>
<tr class="odd">
<td align="center">-19000</td>
<td align="center">-394.9</td>
</tr>
<tr class="even">
<td align="center">-19955</td>
<td align="center">1561</td>
</tr>
<tr class="odd">
<td align="center">-21758</td>
<td align="center">1435</td>
</tr>
<tr class="even">
<td align="center">-18369</td>
<td align="center">2094</td>
</tr>
<tr class="odd">
<td align="center">17182</td>
<td align="center">-988.6</td>
</tr>
<tr class="even">
<td align="center">17455</td>
<td align="center">-28.01</td>
</tr>
<tr class="odd">
<td align="center">22613</td>
<td align="center">-11249</td>
</tr>
<tr class="even">
<td align="center">19312</td>
<td align="center">6807</td>
</tr>
<tr class="odd">
<td align="center">16493</td>
<td align="center">-792.7</td>
</tr>
<tr class="even">
<td align="center">30111</td>
<td align="center">5392</td>
</tr>
</tbody>
</table>
<p>Table 5: MDS coordinates used for plotting the distances using Poisson Distance</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="EDA.html#cb29-1" tabindex="-1"></a><span class="co"># Separate the annotation factor (as the variable name is used as label)</span></span>
<span id="cb29-2"><a href="EDA.html#cb29-2" tabindex="-1"></a>groups <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each=</span><span class="dv">3</span>), </span>
<span id="cb29-3"><a href="EDA.html#cb29-3" tabindex="-1"></a>                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;di_IPSC&quot;</span>, <span class="st">&quot;tri_IPSC&quot;</span>, <span class="st">&quot;di_NEUR&quot;</span>, <span class="st">&quot;tri_NEUR&quot;</span>))</span>
<span id="cb29-4"><a href="EDA.html#cb29-4" tabindex="-1"></a>coldata <span class="ot">&lt;-</span> <span class="fu">names</span>(counts)</span>
<span id="cb29-5"><a href="EDA.html#cb29-5" tabindex="-1"></a></span>
<span id="cb29-6"><a href="EDA.html#cb29-6" tabindex="-1"></a><span class="co"># Create the plot using ggplot</span></span>
<span id="cb29-7"><a href="EDA.html#cb29-7" tabindex="-1"></a><span class="fu">ggplot</span>(mdsPoisData, <span class="fu">aes</span>(x_coord, y_coord, <span class="at">color =</span> groups, <span class="at">label =</span> coldata)) <span class="sc">+</span> </span>
<span id="cb29-8"><a href="EDA.html#cb29-8" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb29-9"><a href="EDA.html#cb29-9" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&#39;Multi Dimensional Scaling&#39;</span>) <span class="sc">+</span></span>
<span id="cb29-10"><a href="EDA.html#cb29-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Poisson Distance&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Poisson Distance&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-11"><a href="EDA.html#cb29-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:mdsPoissonPlot"></span>
<img src="gene_expression_files/figure-html/mdsPoissonPlot-1.png" alt="Multi Dimensional Scaling - Poisson Distance for all samples" width="672" />
<p class="caption">
Figure 3.5: Multi Dimensional Scaling - Poisson Distance for all samples
</p>
</div>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="EDA.html#cb30-1" tabindex="-1"></a><span class="do">## Using base-R plot and legend functions:</span></span>
<span id="cb30-2"><a href="EDA.html#cb30-2" tabindex="-1"></a><span class="co"># plot(mdsPoisData, col=rep(myColors, each=3), pch=20, lwd=2)</span></span>
<span id="cb30-3"><a href="EDA.html#cb30-3" tabindex="-1"></a><span class="co"># legend(x=-20000, y=11000, legend = levels(groups), col=myColors, pch=20)</span></span></code></pre></div>
<p>We clearly see a separation on cell type and a less clear separation on ploidy. The spread within the disomic groups is much lower compared to the trisomic groups. Note that the y-axis range is about a 4th of the x-axis range. The sample <code>di_NEUR_r3</code> shows a large difference in the MDS plot. Once we have a set of genes identified as being differentially expressed we could repeat this step with the expectation of a more clear clustering.</p>
</div>
</div>
<div id="cleaning-data" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Cleaning Data</h2>
<p>Conclude this chapter by <em>cleaning</em> your dataset if the visualizations show the necessity for this. Cleaning in this case means <em>removing</em> complete samples if they can be classified as an outlier <em>within</em> its group. As with most tasks during this course, there is no clear advice on when to decide to remove one or more samples. The only clear rule is that each group <em>must</em> retain at least three samples. If one of the three samples visibly deviates from the other replicates, even after normalization, it will stay in your data set and it should be mentioned in your analysis report/ final article that noise <em>may</em> be introduced by this sample.
<strong>Note</strong>: Once you are satisfied with the data and reported on your findings, we do not return to any of these steps in the next chapters. If there are mentions of creating a heatmap for instance, this means a heatmap of <em>expression data</em> instead of the <em>sample distances</em> we’ve shown in this chapter.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-R-edgeR" class="csl-entry">
Chen, Yunshun, Aaron Lun, Davis McCarthy, Xiaobei Zhou, Mark Robinson, and Gordon Smyth. 2018. <em>edgeR: Empirical Analysis of Digital Gene Expression Data in r</em>. <a href="http://bioinf.wehi.edu.au/edgeR">http://bioinf.wehi.edu.au/edgeR</a>.
</div>
<div id="ref-R-pander" class="csl-entry">
Daróczi, Gergely, and Roman Tsegelskyi. 2017. <em>Pander: An r ’Pandoc’ Writer</em>. <a href="https://CRAN.R-project.org/package=pander">https://CRAN.R-project.org/package=pander</a>.
</div>
<div id="ref-R-DESeq2" class="csl-entry">
Love, Michael, Simon Anders, and Wolfgang Huber. 2017. <em>DESeq2: Differential Gene Expression Analysis Based on the Negative Binomial Distribution</em>. <a href="https://github.com/mikelove/DESeq2">https://github.com/mikelove/DESeq2</a>.
</div>
</div>
<p style="text-align: center;">
<a href="from-reads-to-counts.html"><button class="btn btn-default">Previous</button></a>
<a href="chapter-4.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
